# LDA and Spectral Clustering (mining approach) Notebook

This model uses the same basic structure as the previous group, but replaces HDBSCAN with Spectral Clustering

## Workflow Outline:
We leverage two parallel pipelines, that are combined to recommend median frequencies to explore after each model has completed training and prediction.

All projects for this phase of the overall pipeline are 'line' projects.

### Frequency Mining Pipeline
* OPTIONAL: remove projects with > 26.5 measurements **CURRENTLY REMOVING**
    * Tested both options, hit rate accuracies did not increase significantly to offset 1k cluster add

* Run projects through LDA to generate topic model with $N=50$ topics
    * Currently using count vectorization of combined title and abstract with lemmatized_no_sw_text
* Group projects to max topic by taking argmax of document-topic table
* Run Spectral Clustering on each of the topics to create measurement clusters, referred to as "areas of interest"
    * Currently areas of interest are taken from min and max median frequency for each cluster generated
    * NOTE: each of the 50 Spectral Clustering models can (and probably should) be tuned individually
        * We should make sure generated clusters are not too large unless it makes sense
            * E.G. a large cluster from 700-750GHz might make sense since measurements in this range are generally sparse
    * Any cluster that spans bands is broken up into smaller clusters
        * If the remaining measurments do not meet the minimum point requirements to be a cluster they are assigned back to noise

### Band Prediction Pipeline
* OPTIONAL: remove projects with > 26.5 measurements 
* Predict band for project with Naive Bayes
    * Currently using TF-IDF vectorization of combined title and abstract with lemmatized_no_sw_text
* Choose band(s) using hard classification into one or two bands
    * We remove band 2 entirely because there are so few 
    * We do this to be able to give a final hit rate of appx. 75%
        * This shows we have a good prediction model to match projects to band
* Ultimately we will use probability vector output (not hard classification) to order mined recommendations by full band prediction

In [ ]:
import pandas as pd
import numpy as np
import pandas as pd
import plotly_express as px
from ast import literal_eval
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.cluster import HDBSCAN, OPTICS, SpectralClustering # various testing methods
from sklearn.mixture import GaussianMixture

SEED = 42

## Read data
Training and testing projects and measurements are created in the /data/Data_Ingestion.ipynb notebook

In [2]:
train_projects = pd.read_csv("C:/Users/krish/OneDrive/Desktop/Grad School Shit/Real Grad School/Spring 2025/Capstone/NRAO_ALMA_MSDS_Capstone_2024/data/raw_data/train_projects.csv")
train_projects = train_projects.set_index('project_code')
train_projects.shape

(2383, 12)

In [3]:
test_projects = pd.read_csv("C:/Users/krish/OneDrive/Desktop/Grad School Shit/Real Grad School/Spring 2025/Capstone/NRAO_ALMA_MSDS_Capstone_2024/data/raw_data/test_projects.csv")
test_projects = test_projects.set_index('project_code')
test_projects.shape

(795, 12)

In [4]:
train_measurements = pd.read_csv('C:/Users/krish/OneDrive/Desktop/Grad School Shit/Real Grad School/Spring 2025/Capstone/NRAO_ALMA_MSDS_Capstone_2024/data/raw_data/train_measurements.zip')
train_measurements = train_measurements.set_index('project_code')
train_measurements.shape

(17638, 16)

In [6]:
train_measurements.head(5)[['low_freq', 'med_freq', 'high_freq']]

                low_freq  med_freq  high_freq
project_code
2016.1.01288.S    137.06   137.995     138.93
2016.1.01288.S    138.87   139.800     140.73
2016.1.01288.S    149.17   150.100     151.03
2016.1.01288.S    150.97   151.905     152.84
2016.1.01288.S    143.87   144.805     145.74

In [52]:
test_measurements = pd.read_csv('C:/Users/krish/OneDrive/Desktop/Grad School Shit/Real Grad School/Spring 2025/Capstone/NRAO_ALMA_MSDS_Capstone_2024/data/raw_data/test_measurements.zip')
test_measurements = test_measurements.set_index('project_code')
test_measurements.shape

(5844, 16)

## Read in band predictions
This data frame gives a list from least likely band to most likely band for each test project from the Band Classification part of the project

In [53]:
band_predictions = pd.read_csv('../../data/model_outputs/band_prediction.csv')
band_predictions = band_predictions.set_index('project_code')
band_predictions.head()

                            band_predictions
project_code
2016.1.00485.S  [1, 10, 9, 5, 4, 7, 6, 8, 3]
2017.1.00824.S  [1, 10, 8, 5, 9, 4, 7, 3, 6]
2015.1.01088.S  [1, 10, 9, 8, 5, 4, 7, 6, 3]
2013.1.00781.S  [1, 9, 10, 8, 5, 7, 3, 4, 6]
2016.1.00800.S  [1, 10, 5, 4, 8, 9, 3, 6, 7]

## Band Cutoffs from ALMA

In [54]:
band_cutoffs = [35, 51, 84, 125, 158, 211, 275, 385, 602, 787]

## LDA Model

### Create training and testing text groups to fit LDA

In [55]:
train_texts = train_projects.lemmatized_no_sw_text
test_texts = test_projects.lemmatized_no_sw_text

### LDA class

In [56]:
class LDA_Model:
    def __init__(self, N_topics=50):
        self.N_topics = N_topics
        self.countVectorizer = CountVectorizer()
        self.lda = LatentDirichletAllocation(n_components=self.N_topics, random_state=SEED)
    
    def fit(self, corpus):
        termFrequency = self.countVectorizer.fit_transform(corpus)
        self.lda.fit(termFrequency)
        return self.lda.transform(termFrequency)

    # Additional method to transform new data
    def transform(self, corpus):
        termFrequency = self.countVectorizer.transform(corpus)
        return self.lda.transform(termFrequency)

#### Initialize Model

In [57]:
lda_model = LDA_Model(N_topics=50)

#### Fit model on training set

In [58]:
train_topics = lda_model.fit(train_texts)

In [59]:
words = lda_model.countVectorizer.get_feature_names_out()

### Inspect top words for topics to see if they are salient
We can also use these later in user-facing tools for transparency

In [60]:
N = 10 #number of top words to show
topic_components = lda_model.lda.components_

for topic_idx, topic in enumerate(topic_components):
    print(f"Topic {topic_idx}:")
    # Get the indices of the top N words for this topic
    top_word_indices = topic.argsort()[-N:][::-1]
    # Print these words with their weights
    for word_idx in top_word_indices:
        print(f"{words[word_idx]} (weight: {topic[word_idx]:.2f})")
    print("\n")

Topic 0:
line (weight: 57.87)
bd (weight: 48.98)
compact (weight: 36.90)
velocity (weight: 26.63)
nucleus (weight: 24.94)
con (weight: 21.02)
obscure (weight: 17.56)
bds (weight: 17.02)
variation (weight: 16.27)
nuclei (weight: 15.03)


Topic 1:
dust (weight: 188.60)
gas (weight: 122.90)
ci (weight: 59.72)
grain (weight: 40.69)
evolution (weight: 39.17)
observation (weight: 36.21)
star (weight: 30.49)
carbon (weight: 30.10)
destruction (weight: 28.51)
study (weight: 26.06)


Topic 2:
agb (weight: 141.51)
star (weight: 127.80)
mass (weight: 107.10)
loss (weight: 81.86)
bipolar (weight: 70.32)
outflow (weight: 61.83)
jet (weight: 59.40)
nebula (weight: 53.18)
planetary (weight: 40.83)
wind (weight: 40.55)


Topic 3:
system (weight: 74.58)
debris (weight: 63.54)
belt (weight: 47.11)
planet (weight: 46.05)
disk (weight: 36.87)
collision (weight: 34.83)
structure (weight: 34.27)
disc (weight: 30.83)
observation (weight: 30.48)
scale (weight: 28.42)


Topic 4:
galaxy (weight: 212.35)
scale (weight: 184.28)
molecular (weight: 160.69)
gas (weight: 141.24)
star (weight: 126.73)
formation (weight: 103.67)
mass (weight: 100.81)
property (weight: 85.81)
relation (weight: 84.20)
study (weight: 78.01)


Topic 5:
quasar (weight: 323.85)
host (weight: 121.62)
qso (weight: 74.59)
galaxy (weight: 69.99)
qsos (weight: 53.54)
observation (weight: 53.12)
line (weight: 51.06)
mass (weight: 42.72)
evolution (weight: 39.82)
black (weight: 34.66)


Topic 6:
system (weight: 209.51)
binary (weight: 208.43)
disk (weight: 184.63)
star (weight: 148.05)
formation (weight: 72.56)
observation (weight: 72.08)
multiplicity (weight: 61.24)
stellar (weight: 49.71)
multiple (weight: 47.83)
around (weight: 47.27)


Topic 7:
maser (weight: 214.53)
sio (weight: 112.27)
line (weight: 41.68)
kl (weight: 37.38)
orion (weight: 31.56)
host (weight: 31.24)
mass (weight: 26.09)
study (weight: 21.13)
observation (weight: 20.71)
trace (weight: 19.81)


Topic 8:
disk (weight: 119.07)
system (weight: 101.81)
binary (weight: 82.27)
streamer (weight: 68.22)
formation (weight: 54.47)
circumbinary (weight: 34.50)
comet (weight: 32.88)
form (weight: 31.07)
close (weight: 28.60)
observation (weight: 27.10)


Topic 9:
disk (weight: 409.84)
wind (weight: 107.45)
star (weight: 86.13)
mass (weight: 68.97)
accretion (weight: 62.46)
line (weight: 59.83)
angular (weight: 58.65)
velocity (weight: 55.98)
observation (weight: 55.68)
spiral (weight: 50.90)


Topic 10:
star (weight: 920.06)
formation (weight: 624.03)
galaxy (weight: 390.57)
gas (weight: 343.61)
dense (weight: 262.56)
form (weight: 228.26)
mass (weight: 214.71)
cloud (weight: 205.44)
cluster (weight: 194.64)
observation (weight: 186.41)


Topic 11:
disc (weight: 113.26)
tidal (weight: 19.33)
tdgs (weight: 19.02)
prestellar (weight: 18.20)
dwarf (weight: 17.69)
observation (weight: 16.43)
galaxy (weight: 14.69)
nearby (weight: 10.75)
ci (weight: 10.26)
star (weight: 7.79)


Topic 12:
gas (weight: 428.49)
molecular (weight: 394.80)
ci (weight: 196.85)
study (weight: 145.88)
line (weight: 145.60)
galaxy (weight: 131.01)
tracer (weight: 129.08)
star (weight: 126.47)
cloud (weight: 110.91)
formation (weight: 97.52)


Topic 13:
gas (weight: 413.46)
molecular (weight: 237.37)
galaxy (weight: 210.68)
observation (weight: 148.91)
star (weight: 113.04)
formation (weight: 91.50)
scale (weight: 79.11)
massive (weight: 65.66)
main (weight: 61.77)
cgm (weight: 58.02)


Topic 14:
cold (weight: 91.37)
gas (weight: 69.92)
cool (weight: 59.43)
cluster (weight: 56.93)
molecular (weight: 42.32)
galaxy (weight: 41.47)
line (weight: 27.30)
flow (weight: 25.07)
ice (weight: 19.67)
central (weight: 19.65)


Topic 15:
dark (weight: 69.81)
mass (weight: 62.18)
matter (weight: 53.77)
line (weight: 38.58)
observation (weight: 31.84)
galaxy (weight: 26.69)
lens (weight: 26.14)
lensed (weight: 21.35)
infrared (weight: 21.17)
gas (weight: 19.87)


Topic 16:
dust (weight: 68.60)
star (weight: 67.08)
observation (weight: 40.13)
region (weight: 40.13)
rich (weight: 37.60)
carbon (weight: 31.44)
agb (weight: 29.41)
irc (weight: 27.87)
line (weight: 27.61)
observe (weight: 27.35)


Topic 17:
galaxy (weight: 547.45)
gas (weight: 336.39)
star (weight: 232.03)
formation (weight: 164.53)
massive (weight: 137.73)
quench (weight: 117.74)
molecular (weight: 90.22)
stellar (weight: 88.81)
observation (weight: 75.61)
feedback (weight: 74.73)


Topic 18:
star (weight: 130.19)
gas (weight: 129.25)
molecular (weight: 100.02)
galaxy (weight: 95.28)
formation (weight: 77.24)
form (weight: 51.78)
region (weight: 51.20)
strip (weight: 46.95)
observation (weight: 41.99)
pressure (weight: 37.47)


Topic 19:
disk (weight: 988.84)
planet (weight: 463.01)
formation (weight: 163.29)
dust (weight: 147.96)
young (weight: 133.62)
protoplanetary (weight: 124.81)
planetary (weight: 124.23)
mass (weight: 114.48)
cavity (weight: 113.31)
around (weight: 112.53)


Topic 20:
jet (weight: 379.05)
magnetic (weight: 329.34)
polarization (weight: 174.30)
field (weight: 157.70)
observation (weight: 130.45)
scale (weight: 67.33)
radio (weight: 63.14)
launch (weight: 50.21)
morphology (weight: 46.83)
accretion (weight: 46.39)


Topic 21:
outflow (weight: 436.84)
protostars (weight: 196.54)
envelope (weight: 180.05)
protostellar (weight: 172.11)
observation (weight: 138.54)
core (weight: 125.91)
mass (weight: 123.44)
protostar (weight: 118.90)
class (weight: 115.45)
star (weight: 103.01)


Topic 22:
hco (weight: 80.29)
dense (weight: 67.39)
absorption (weight: 66.28)
molecular (weight: 53.75)
gas (weight: 52.27)
diffuse (weight: 51.28)
line (weight: 38.93)
density (weight: 31.37)
cloud (weight: 28.54)
chemical (weight: 27.16)


Topic 23:
disk (weight: 210.37)
gas (weight: 112.95)
debris (weight: 93.57)
system (weight: 55.11)
star (weight: 49.49)
observation (weight: 46.84)
infall (weight: 39.51)
young (weight: 35.61)
planet (weight: 35.32)
mass (weight: 34.44)


Topic 24:
core (weight: 657.52)
filament (weight: 460.38)
mass (weight: 279.66)
massive (weight: 262.22)
star (weight: 216.30)
scale (weight: 206.80)
dense (weight: 185.91)
fragmentation (weight: 178.68)
formation (weight: 171.55)
cloud (weight: 170.16)


Topic 25:
bar (weight: 164.70)
gmcs (weight: 94.72)
molecular (weight: 69.64)
spiral (weight: 65.12)
galaxy (weight: 59.56)
arm (weight: 47.99)
giant (weight: 33.50)
gas (weight: 30.75)
study (weight: 30.40)
galactic (weight: 28.27)


Topic 26:
torus (weight: 131.38)
ci (weight: 46.65)
line (weight: 29.69)
image (weight: 20.50)
wind (weight: 19.29)
molecular (weight: 16.95)
continuum (weight: 16.80)
circinus (weight: 15.73)
circumnuclear (weight: 15.68)
observation (weight: 14.26)


Topic 27:
hole (weight: 220.52)
black (weight: 181.82)
sgr (weight: 82.36)
center (weight: 76.65)
supermassive (weight: 67.89)
observation (weight: 67.57)
galactic (weight: 65.80)
accretion (weight: 57.16)
provide (weight: 39.49)
sgra (weight: 35.02)


Topic 28:
observation (weight: 47.08)
magnetic (weight: 44.28)
star (weight: 40.41)
mass (weight: 31.13)
line (weight: 29.20)
zeeman (weight: 29.15)
snrs (weight: 25.65)
observe (weight: 24.56)
effect (weight: 24.26)
stellar (weight: 24.03)


Topic 29:
shock (weight: 160.43)
ray (weight: 101.88)
grb (weight: 75.02)
host (weight: 67.72)
supernova (weight: 64.31)
molecular (weight: 60.64)
remnant (weight: 55.99)
cloud (weight: 55.37)
study (weight: 48.09)
cosmic (weight: 46.59)


Topic 30:
molecule (weight: 76.80)
disk (weight: 57.13)
observe (weight: 34.13)
formation (weight: 27.09)
chemistry (weight: 26.93)
organic (weight: 23.40)
solar (weight: 23.21)
abundance (weight: 22.55)
protoplanetary (weight: 21.08)
origin (weight: 20.90)


Topic 31:
nitrogen (weight: 37.32)
titan (weight: 32.93)
hc (weight: 32.62)
region (weight: 23.68)
atmosphere (weight: 21.67)
phase (weight: 20.47)
ammonia (weight: 18.89)
chemistry (weight: 15.82)
observation (weight: 15.71)
specie (weight: 15.68)


Topic 32:
deuteration (weight: 21.55)
disk (weight: 19.64)
towards (weight: 16.79)
observe (weight: 14.78)
formation (weight: 14.36)
observation (weight: 13.61)
protostars (weight: 12.63)
star (weight: 12.33)
class (weight: 11.88)
scale (weight: 11.80)


Topic 33:
outflow (weight: 168.08)
molecular (weight: 107.30)
observation (weight: 70.51)
galaxy (weight: 68.93)
gas (weight: 59.56)
observe (weight: 34.77)
massive (weight: 27.43)
line (weight: 22.86)
spt (weight: 21.38)
ulirgs (weight: 20.27)


Topic 34:
water (weight: 306.43)
snowline (weight: 61.07)
deuterium (weight: 50.20)
line (weight: 42.25)
fractionation (weight: 35.41)
hdo (weight: 35.02)
observation (weight: 33.74)
deuterated (weight: 27.67)
vapor (weight: 25.32)
grain (weight: 25.22)


Topic 35:
disk (weight: 218.87)
dust (weight: 49.72)
protoplanetary (weight: 44.65)
turbulence (weight: 43.33)
around (weight: 37.56)
gas (weight: 35.87)
solar (weight: 35.56)
upper (weight: 32.31)
evolution (weight: 31.03)
observation (weight: 30.64)


Topic 36:
jet (weight: 97.34)
star (weight: 66.74)
formation (weight: 54.24)
gas (weight: 51.76)
radio (weight: 44.70)
ism (weight: 38.17)
galaxy (weight: 37.90)
study (weight: 30.33)
interaction (weight: 27.30)
molecular (weight: 26.54)


Topic 37:
mass (weight: 127.72)
chemical (weight: 42.42)
chain (weight: 41.92)
protostars (weight: 38.13)
wccc (weight: 34.02)
source (weight: 32.14)
carbon (weight: 28.55)
protostellar (weight: 25.06)
chemistry (weight: 21.50)
corino (weight: 21.12)


Topic 38:
gas (weight: 30.99)
galaxy (weight: 21.51)
disk (weight: 18.22)
molecular (weight: 18.17)
observation (weight: 16.29)
formation (weight: 14.42)
mass (weight: 12.21)
obscure (weight: 10.19)
transition (weight: 10.16)
line (weight: 9.73)


Topic 39:
chemical (weight: 336.81)
chemistry (weight: 180.77)
molecule (weight: 173.43)
ch (weight: 171.05)
organic (weight: 138.96)
gas (weight: 137.26)
abundance (weight: 131.50)
composition (weight: 124.90)
complex (weight: 110.98)
specie (weight: 103.01)


Topic 40:
surface (weight: 39.28)
atmosphere (weight: 34.87)
magnetic (weight: 29.15)
atmospheric (weight: 28.48)
sulphur (weight: 28.02)
jupiter (weight: 23.86)
observation (weight: 23.68)
star (weight: 20.72)
vertical (weight: 20.17)
structure (weight: 19.62)


Topic 41:
star (weight: 569.48)
cluster (weight: 361.19)
formation (weight: 330.02)
cloud (weight: 309.28)
mass (weight: 287.74)
massive (weight: 258.66)
form (weight: 245.19)
region (weight: 238.93)
clump (weight: 121.14)
observation (weight: 96.09)


Topic 42:
line (weight: 107.24)
accretion (weight: 68.45)
burst (weight: 60.42)
luminosity (weight: 50.93)
observation (weight: 43.66)
episodic (weight: 41.82)
outburst (weight: 36.25)
fu (weight: 27.20)
snow (weight: 22.91)
recombination (weight: 22.25)


Topic 43:
disk (weight: 1183.27)
dust (weight: 378.84)
observation (weight: 337.21)
planet (weight: 270.23)
formation (weight: 244.02)
around (weight: 197.05)
gas (weight: 187.85)
structure (weight: 183.59)
grain (weight: 151.40)
mass (weight: 144.15)


Topic 44:
sulfur (weight: 46.01)
cluster (weight: 37.51)
specie (weight: 28.35)
formation (weight: 18.46)
gas (weight: 17.96)
observe (weight: 17.35)
bearing (weight: 17.24)
refractory (weight: 15.79)
observation (weight: 14.45)
molecule (weight: 12.64)


Topic 45:
star (weight: 87.57)
mass (weight: 69.63)
observation (weight: 55.99)
accretion (weight: 54.00)
continuum (weight: 53.60)
dust (weight: 53.51)
system (weight: 53.37)
ring (weight: 52.83)
disk (weight: 50.29)
orbit (weight: 46.04)


Topic 46:
agn (weight: 520.79)
gas (weight: 432.76)
outflow (weight: 378.40)
molecular (weight: 373.56)
feedback (weight: 258.59)
galaxy (weight: 222.63)
observation (weight: 190.57)
scale (weight: 118.21)
region (weight: 110.69)
line (weight: 107.03)


Topic 47:
gas (weight: 652.14)
galaxy (weight: 443.41)
molecular (weight: 243.87)
merger (weight: 152.95)
observation (weight: 127.51)
starburst (weight: 125.64)
study (weight: 92.31)
dust (weight: 87.79)
formation (weight: 85.63)
disk (weight: 85.56)


Topic 48:
mass (weight: 392.07)
disk (weight: 201.14)
hole (weight: 116.35)
black (weight: 113.29)
gas (weight: 99.93)
measurement (weight: 87.41)
rotation (weight: 87.23)
smbh (weight: 77.07)
galaxy (weight: 56.31)
type (weight: 53.73)


Topic 49:
galaxy (weight: 981.17)
cii (weight: 413.55)
line (weight: 392.89)
redshift (weight: 345.34)
dust (weight: 316.08)
star (weight: 273.82)
observation (weight: 227.11)
formation (weight: 164.11)
continuum (weight: 163.96)
form (weight: 154.69)

### Inspect training document-topic data frames

In [61]:
train_doc_topic = pd.DataFrame(train_topics)
train_doc_topic = train_doc_topic.set_index(train_texts.index.values)
train_doc_topic.head()

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
2016.1.01288.S,0.000392,0.000392,0.000392,0.000392,0.000392,0.065492,0.000392,0.000392,0.000392,0.000392,...,0.000392,0.000392,0.000392,0.000392,0.000392,0.000392,0.464354,0.000392,0.000392,0.000392
2018.1.01077.S,0.000194,0.000194,0.000194,0.000194,0.000194,0.000194,0.000194,0.000194,0.000194,0.000194,...,0.000194,0.000194,0.000194,0.000194,0.000194,0.000194,0.000194,0.376111,0.000194,0.000194
2018.1.00437.S,0.000192,0.000192,0.000192,0.127172,0.000192,0.000192,0.000192,0.000192,0.000192,0.000192,...,0.000192,0.000192,0.000192,0.000192,0.000192,0.000192,0.000192,0.000192,0.000192,0.000192
2021.1.00637.S,0.000222,0.000222,0.000222,0.000222,0.000222,0.000222,0.000222,0.000222,0.000222,0.000222,...,0.000222,0.000222,0.000222,0.000222,0.000222,0.000222,0.000222,0.000222,0.000222,0.000222
2012.1.00786.S,0.000171,0.000171,0.192147,0.000171,0.000171,0.000171,0.000171,0.740628,0.000171,0.000171,...,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171

### Match test data into topics

In [62]:
test_topics = lda_model.transform(test_texts)

### Inspect testing document-topic data frames

In [63]:
test_doc_topic= pd.DataFrame(test_topics.tolist())
test_doc_topic= test_doc_topic.set_index(test_texts.index.values)
test_doc_topic.head(5)

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
2016.1.00485.S,0.000215,0.000215,0.000215,0.029035,0.000215,0.000215,0.000215,0.000215,0.000215,0.000215,...,0.000215,0.000215,0.000215,0.000215,0.000215,0.000215,0.000215,0.031655,0.000215,0.113737
2017.1.00824.S,0.000169,0.098192,0.080003,0.000169,0.000169,0.000169,0.000169,0.000169,0.000169,0.000169,...,0.000169,0.130644,0.000169,0.140330,0.000169,0.000169,0.000169,0.022981,0.000169,0.000169
2015.1.01088.S,0.188665,0.000211,0.000211,0.000211,0.017753,0.134495,0.000211,0.063180,0.063875,0.000211,...,0.000211,0.000211,0.000211,0.109437,0.000211,0.020642,0.146402,0.000211,0.000211,0.070094
2013.1.00781.S,0.000294,0.000294,0.000294,0.000294,0.000294,0.000294,0.135778,0.000294,0.000294,0.122034,...,0.000294,0.000294,0.000294,0.000294,0.000294,0.000294,0.000294,0.087903,0.000294,0.461476
2016.1.00800.S,0.317005,0.000182,0.000182,0.000182,0.000182,0.000182,0.000182,0.000182,0.000182,0.000182,...,0.000182,0.000182,0.000182,0.076003,0.000182,0.000182,0.000182,0.000182,0.052253,0.000182

### Group documents to highest matching topic

Combine project topic vector frames for convenience.
* Note you can subset this dataframe to train and test texts using `proj_topics.loc[train_texts.index]`

In [64]:
train_texts = pd.DataFrame(train_texts)
test_texts = pd.DataFrame(test_texts)
proj_topics = pd.concat([train_doc_topic, test_doc_topic])
proj_topics.head(5)

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
2016.1.01288.S,0.000392,0.000392,0.000392,0.000392,0.000392,0.065492,0.000392,0.000392,0.000392,0.000392,...,0.000392,0.000392,0.000392,0.000392,0.000392,0.000392,0.464354,0.000392,0.000392,0.000392
2018.1.01077.S,0.000194,0.000194,0.000194,0.000194,0.000194,0.000194,0.000194,0.000194,0.000194,0.000194,...,0.000194,0.000194,0.000194,0.000194,0.000194,0.000194,0.000194,0.376111,0.000194,0.000194
2018.1.00437.S,0.000192,0.000192,0.000192,0.127172,0.000192,0.000192,0.000192,0.000192,0.000192,0.000192,...,0.000192,0.000192,0.000192,0.000192,0.000192,0.000192,0.000192,0.000192,0.000192,0.000192
2021.1.00637.S,0.000222,0.000222,0.000222,0.000222,0.000222,0.000222,0.000222,0.000222,0.000222,0.000222,...,0.000222,0.000222,0.000222,0.000222,0.000222,0.000222,0.000222,0.000222,0.000222,0.000222
2012.1.00786.S,0.000171,0.000171,0.192147,0.000171,0.000171,0.000171,0.000171,0.740628,0.000171,0.000171,...,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171

### Take highest matching topic for each project

In [65]:
proj_topics['max_topic'] = proj_topics.apply(lambda x: x.argmax(), axis=1)

### Create data frame with project id and max topic

In [66]:
proj_max_topic = proj_topics['max_topic'].to_frame()
proj_max_topic.head()

                max_topic
2016.1.01288.S         46
2018.1.01077.S         37
2018.1.00437.S         17
2021.1.00637.S         13
2012.1.00786.S          7

In [67]:
proj_max_topic.max_topic.value_counts().to_frame().sort_index()

           count
max_topic
0             23
1             29
2             42
3             24
4             47
5             37
6             50
7             25
8             28
9             74
10           218
11             7
12           150
13           120
14            16
15            28
16            40
17           109
18            46
19           130
20            53
21            99
22            20
23            46
24           132
25            23
26            17
27            33
28            30
29            28
30            26
31            22
32            16
33            31
34            25
35            27
36            34
37            18
38            11
39           106
40            20
41           112
42            30
43           249
44            15
45            55
46           188
47           113
48            63
49           293

### Inspect some topic stats

In [68]:
proj_max_topic.value_counts().describe()

count     50.0000
mean      63.5600
std       64.2737
min        7.0000
25%       24.2500
50%       33.5000
75%       92.7500
max      293.0000
Name: count, dtype: float64

There are a few topics that match to a large number of documents. Perhaps we need a better topic model or to group documents by project_topic vector similarity.

### Eyeball comparison of documents by max topic
This requires looking at the online explorer since printing out abstracts in here gets messy.

In [69]:
proj_max_topic[proj_max_topic.max_topic == 3].head()

                max_topic
2022.1.00793.S          3
2015.1.01260.S          3
2017.1.00167.S          3
2019.1.01443.T          3
2015.1.00032.S          3

### Add `max_topic` to `measurements` frame to be able to group measurements by max topic

In [70]:
train_measurements = pd.merge(train_measurements, proj_max_topic, left_index=True, right_index=True)

### Generate test projects measurements
This will be useful for calculating hit rates to evaluate model performance.

**NOTE!!!**
You should not sort these, however tempting. We need to preserve the relationships of the entries to not lose measurement information.

In [71]:
test_proj_meas = test_measurements.loc[test_texts.index]
test_proj_meas = test_proj_meas.groupby(test_proj_meas.index)\
    .agg({
        'low_freq': lambda x: round(x, 4).tolist(),
        'high_freq': lambda x: round(x, 4).tolist(),
        'med_freq': lambda x: round(x, 4).tolist(),
        'diff_freq': lambda x: round(x, 4).tolist()
    })
test_proj_meas.head()

,low_freq,high_freq,med_freq,diff_freq
project_code,,,,
2011.0.00010.S,"[90.38, 90.7, 91.69, 92.89, 217.59, 218.67, 21...","[90.62, 90.93, 91.92, 93.12, 218.53, 219.6, 21...","[90.5, 90.815, 91.805, 93.005, 218.06, 219.135...","[0.24, 0.23, 0.23, 0.23, 0.94, 0.93, 0.94, 0.9..."
2011.0.00064.S,"[288.96, 290.79, 300.84, 302.71, 288.94, 290.7...","[290.84, 292.67, 302.71, 304.59, 290.82, 292.6...","[289.9, 291.73, 301.775, 303.65, 289.88, 291.7...","[1.88, 1.88, 1.87, 1.88, 1.88, 1.87, 1.88, 1.87]"
2011.0.00121.S,"[319.07, 320.48, 319.83, 319.36, 319.71, 316.59]","[320.94, 322.35, 321.71, 321.24, 321.58, 318.47]","[320.005, 321.415, 320.77, 320.3, 320.645, 317...","[1.87, 1.87, 1.88, 1.88, 1.87, 1.88]"
2011.0.00136.S,"[335.29, 335.98, 345.67, 346.47]","[335.52, 336.22, 345.91, 346.7]","[335.405, 336.1, 345.79, 346.585]","[0.23, 0.24, 0.24, 0.23]"
2011.0.00199.S,"[639.15, 645.41, 657.7, 661.7, 320.98, 322.12,...","[640.11, 646.37, 658.66, 662.66, 321.46, 322.6...","[639.63, 645.89, 658.18, 662.18, 321.22, 322.3...","[0.96, 0.96, 0.96, 0.96, 0.48, 0.48, 0.49, 0.48]"

### Generate train topic measurements
We will use these to engineer 'areas of interest' among topics using Spectral Clustering

**NOTE!!!**
You should not sort these, however tempting. We need to preserve the relationships of the entries to not lose measurement information.

In [72]:
train_measurements.head()

,project_title,project_abstract,fs_type,low_freq,high_freq,science_category,science_keyword,band,target,diff_freq,med_freq,raw_text,standardized_text,no_sw_text,lemmatized_sw_text,lemmatized_no_sw_text,max_topic
project_code,,,,,,,,,,,,,,,,,
2016.1.01288.S,The molecular gas properties of radio-AGN at z...,Energetic feedback from AGN is believed to pla...,line,137.06,138.93,Active galaxies,"Outflows, jets, feedback",4.0,1,1.87,137.995,The molecular gas properties of radio-AGN at z...,the molecular gas properties of radio agn at z...,molecular gas properties radio agn z energetic...,the molecular gas property of radio agn at z e...,molecular gas property radio agn z energetic f...,46
2016.1.01288.S,The molecular gas properties of radio-AGN at z...,Energetic feedback from AGN is believed to pla...,line,138.87,140.73,Active galaxies,"Outflows, jets, feedback",4.0,1,1.86,139.800,The molecular gas properties of radio-AGN at z...,the molecular gas properties of radio agn at z...,molecular gas properties radio agn z energetic...,the molecular gas property of radio agn at z e...,molecular gas property radio agn z energetic f...,46
2016.1.01288.S,The molecular gas properties of radio-AGN at z...,Energetic feedback from AGN is believed to pla...,line,149.17,151.03,Active galaxies,"Outflows, jets, feedback",4.0,1,1.86,150.100,The molecular gas properties of radio-AGN at z...,the molecular gas properties of radio agn at z...,molecular gas properties radio agn z energetic...,the molecular gas property of radio agn at z e...,molecular gas property radio agn z energetic f...,46
2016.1.01288.S,The molecular gas properties of radio-AGN at z...,Energetic feedback from AGN is believed to pla...,line,150.97,152.84,Active galaxies,"Outflows, jets, feedback",4.0,1,1.87,151.905,The molecular gas properties of radio-AGN at z...,the molecular gas properties of radio agn at z...,molecular gas properties radio agn z energetic...,the molecular gas property of radio agn at z e...,molecular gas property radio agn z energetic f...,46
2016.1.01288.S,The molecular gas properties of radio-AGN at z...,Energetic feedback from AGN is believed to pla...,line,143.87,145.74,Active galaxies,"Outflows, jets, feedback",4.0,1,1.87,144.805,The molecular gas properties of radio-AGN at z...,the molecular gas properties of radio agn at z...,molecular gas properties radio agn z energetic...,the molecular gas property of radio agn at z e...,molecular gas property radio agn z energetic f...,46

In [73]:
train_topic_freqs = train_measurements.loc[train_texts.index]\
    .reset_index()\
    .groupby('max_topic')\
    .agg({
        'project_code': lambda x: x.tolist(), 
        'low_freq': lambda x: round(x, 4).tolist(),
        'high_freq': lambda x: round(x, 4).tolist(),
        'med_freq': lambda x: round(x, 4).tolist(),
        'diff_freq': lambda x: round(x, 4).tolist(),
        'band': lambda x: x.astype('int64').tolist()
    })
train_topic_freqs.head()

,project_code,low_freq,high_freq,med_freq,diff_freq,band
max_topic,,,,,,
0,"[2017.1.00598.S, 2017.1.00598.S, 2017.1.00598....","[257.18, 259.1, 260.42, 262.37, 260.84, 262.79...","[259.04, 260.97, 262.29, 264.24, 262.71, 264.6...","[258.11, 260.035, 261.355, 263.305, 261.775, 2...","[1.86, 1.87, 1.87, 1.87, 1.87, 1.87, 1.87, 1.8...","[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, ..."
1,"[2018.1.00341.S, 2018.1.00341.S, 2018.1.00341....","[342.03, 343.99, 354.03, 355.91, 478.54, 480.5...","[343.9, 345.86, 355.9, 357.79, 480.54, 482.54,...","[342.965, 344.925, 354.965, 356.85, 479.54, 48...","[1.87, 1.87, 1.87, 1.88, 2.0, 2.0, 2.0, 0.25, ...","[7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 6, 6, 6, 6, 6, ..."
2,"[2017.1.00595.S, 2017.1.00595.S, 2017.1.00595....","[330.25, 331.25, 342.52, 345.1, 215.39, 217.28...","[331.25, 333.25, 344.52, 346.1, 217.39, 219.28...","[330.75, 332.25, 343.52, 345.6, 216.39, 218.28...","[1.0, 2.0, 2.0, 1.0, 2.0, 2.0, 1.0, 2.0, 2.0, ...","[7, 7, 7, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, ..."
3,"[2022.1.00793.S, 2022.1.00793.S, 2022.1.00793....","[327.94, 329.94, 339.99, 342.24, 344.24, 354.2...","[329.82, 331.82, 341.86, 344.12, 346.12, 356.1...","[328.88, 330.88, 340.925, 343.18, 345.18, 355....","[1.88, 1.88, 1.87, 1.88, 1.88, 1.87, 1.87, 1.8...","[7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 7, 7, 6, 6, 6, ..."
4,"[2017.1.00707.S, 2017.1.00707.S, 2017.1.00707....","[216.05, 217.07, 217.21, 218.19, 218.45, 219.5...","[216.17, 217.13, 217.27, 218.25, 218.5, 219.59...","[216.11, 217.1, 217.24, 218.22, 218.475, 219.5...","[0.12, 0.06, 0.06, 0.06, 0.05, 0.06, 0.06, 0.1...","[6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 3, 3, 3, 3, 3, ..."

In [74]:
len(train_topic_freqs.loc[10].project_code)

1234

## Cluster cleaning function

How do we handle > 2 band overlaps?

* Currently we just roll with it.
    
* Should call out which topic, and cluster

* Alternatively, throw error <- this is hard because it completely stops any training

In [ ]:
# Code to check for clusters that span at least two bands
def cluster_cleaning(topic_meas_df, min_cluster_size):
    dummy_label = 100000  # Used to make new labels and ensure we're adding new clusters. Cluster labels will be reset eventually

    for clst in np.unique(topic_meas_df.cluster_label):
        if clst != -1:
            # Subset topic measurement dataframe to current cluster
            clst_subset = topic_meas_df[topic_meas_df.cluster_label == clst].sort_values('med_freq')
            
            # Extract band information for cluster subset
            band = np.unique(clst_subset.band)

            # If there are multiple bands in measurements for cluster we want to break them up
            if band.size > 1:
                # Loop over bands in cluster and make a dataframe for each band
                bnd_dict = [clst_subset[clst_subset.band == bnd] for bnd in band]

                # Loop over cluster-band frames
                for df in bnd_dict:
                # Check if number of measurements in this band and cluster is > min_cluster_size
                # If it is less, simply assign those measurements back to noise, since we don't want too small clusters
                # Otherwise, there are enough measurments to keeping "this" part of the cluster, so make a new cluster for it 
                    if df.shape[0] < min_cluster_size:
                        topic_meas_df.loc[df.index, 'cluster_label'] = -1
                    else:
                        topic_meas_df.loc[df.index, 'cluster_label'] = dummy_label
                        dummy_label += 1
                        
    # Re-label clusters to be a continuous range from -1 to N
    new_labels = [n-1 for n in range(len(np.unique(topic_meas_df.cluster_label)))]
    label_counter = 0   # Used to increment through new_labels
    
    # Loop over cluster labels and update them
    for reclust in np.unique(topic_meas_df.cluster_label):
        # Set cluster label to new_labels
        topic_meas_df.loc[topic_meas_df.cluster_label == reclust, 'cluster_label'] = new_labels[label_counter]
        label_counter += 1

## Spectral Clustering Train/Test Code
### Loop over topics and find accuracy measurements

In [ ]:
# Quick test
db = SpectralClustering(n_clusters=10).fit(list(zip(train_topic_freqs.loc[0].med_freq)))

db.labels_

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

array([0, 0, 0, 0, 0, 0, 5, 5, 0, 0, 0, 0, 2, 2, 0, 2, 4, 4, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 9,
       0, 7, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 8, 9, 0, 7, 9, 7, 0, 0, 0, 6, 6, 6,
       6, 0, 3, 3, 0, 0, 5, 8, 0, 0, 5, 5, 0, 0, 0])

In [ ]:
# Spectral Clustering Within all 50 topics

band_prediction_limit = 0               # Number of top band predictions to include. 0 to include all
test_project_hits = 0                   # Hits for all projects if at least one measurement is matched
test_project_meas_hit_rate = []         # List of hit rates by project
topic_cluster_widths = []               # List of cluster widths by topic to ensure generated clusters are not too wide (list of lists)
total_num_clusters = 0                  # List of number of clusters for each topic
topic_cluster_stat_list = []            # List of dataframes with clusters by topic. Used to make a main topic-cluster data frame later
topic_measurement_stat_list = []        # List of dataframes with measurements by topic. Used to make a main topic-measurement data frame later
test_project_hit_list = []              # List of test project hit rates for each cluster

# Loop over topics
for tpc in set(proj_max_topic.max_topic.values):
    # Fit Spectral Clustering for each topic
    # Note that these can be parameterized for each of the topics generated
    db = SpectralClustering()\
        .fit(list(zip(train_topic_freqs.loc[tpc].med_freq)))
    
    # Get labels from Spectral
    labels = db.labels_

    # Create topic-measurement dataframe
    # This has all of the measurements for all of the projects in an LDA topic
    topic_measurement = pd.DataFrame.from_dict({'med_freq':train_topic_freqs.loc[tpc].med_freq,
                                            'band':train_topic_freqs.loc[tpc].band,
                                            'project_code':train_topic_freqs.loc[tpc].project_code,
                                            'cluster_label':labels})
    
    # Format topic_measurement
    topic_measurement = pd.concat({tpc: topic_measurement}, names=['topic'])
    topic_measurement.index.names = ['topic', 'measurement']

    # Append topic_cluster to topic_cluster_stats for analysis later
    topic_measurement_stat_list.append(topic_measurement)
    
    # Clean clusters in topic_measurment, breaking up clusters that span more than one band
    cluster_cleaning(topic_measurement, 5)

    # Generate topic_cluster data frame for this topic
    # Clusters are defined by the minimum and maximum median_freq for all labeled measurements
    topic_cluster = topic_measurement.groupby('cluster_label').agg(
        mean_freq=('med_freq', 'mean'),
        min_freq=('med_freq', 'min'),
        max_freq=('med_freq', 'max'),
        count_freq=('med_freq', 'count'),
        count_proj=('project_code', 'nunique'),
        band_min=('band', 'min'),
        band_max=('band', 'max'),
        band_mode=('band', 'mean')
    )

    # Stat aggregation
    n_projects = topic_cluster.count_proj.sum()
    n_measurements = topic_cluster.count_freq.sum()
    if -1 in topic_cluster.index:
        n_noise = topic_cluster.loc[-1].count_freq
        noise_proportion = n_noise/n_measurements
    else:
        n_noise = 0
        noise_proportion = 0
    signal_proportion = 1-noise_proportion


    # Stat callouts
    print(f'Spectral Results for topic {tpc}')
    print(f'Number of projects in topic: {n_projects}')
    print(f'Total number of measurements: {n_measurements}')
    print(f'Estimated number of noise measurements: {n_noise}')
    print(f'Noise proportion: {round(noise_proportion, 3)}')
    print(f'Signal proportion: {round(signal_proportion, 3)}')

    # Sort index
    topic_cluster = topic_cluster.sort_index()

    # Add width for cleaned clusters
    topic_cluster['width'] = topic_cluster.max_freq - topic_cluster.min_freq

    # Add topic index to topic_cluster
    topic_cluster = pd.concat({tpc: topic_cluster}, names=['topic'])
    topic_cluster.index.names = ['topic', 'cluster']

    # Append topic_cluster to topic_cluster_stats for analysis later
    topic_cluster_stat_list.append(topic_cluster)

    # Testing loop
    # Loop over generated clusters and print cluster stats
    # Initialize list of cluster widths
    # Code to check for clusters that span at least two bands
    cluster_widths = []

    # If there are any measurements in that topic, print stats
    # This if statement is to avoid errors if topics only have noise and no clusters
    if topic_cluster.shape[0] != 0:
        for clst in topic_cluster.index:
            min_freq, max_freq = topic_cluster.loc[clst].min_freq, topic_cluster.loc[clst].max_freq
            cluster_widths.append(max_freq - min_freq)
            total_num_clusters += 1
            if (topic_cluster.loc[clst].band_min != topic_cluster.loc[clst].band_max):
                    print("BAND OVERLAP")
        print('')
        print(f'Topic {tpc} cluster width stats:')
        print(np.round(pd.Series(cluster_widths).describe(), 4))
    else: print('No clusters for this topic')

    # Print cluster data frame with relevant columns for tuning
    print('')
    print(f'Cluster data frame for topic {tpc}')
    with pd.option_context('display.max_rows', None):
        print(topic_cluster[['min_freq', 'max_freq', 'count_freq', 'band_mode', 'width']]\
          .sort_values(['width', 'min_freq'], ascending=False))

    # Get a list of test project codes
    tps = proj_max_topic.loc[test_texts.index].query(f'max_topic == {tpc}')

    #Begin test projects
    print('')
    # print('Begin tests')

    # Loop over test projects
    for tp in tps.index:
        tp_hr = 0   # Hit rate for this specific project
        # Loop over measurements in test project

        # Subset `topic_cluster` to be the top two predicted bands for each project
        topic_cluster_subset = topic_cluster[topic_cluster.band_mode.isin(literal_eval(band_predictions.loc[tp].band_predictions)[-band_prediction_limit:])]
        if topic_cluster.shape[0] != 0:
            print(f'Ratio of recommended clusters to total clusters: {topic_cluster_subset.shape[0]/topic_cluster.shape[0]}')
        else: print(f'No clusters for topic {tpc}')

        for meas in test_proj_meas.loc[tp].med_freq:
            # Loop over clusters in topic
            # Note we have a multi index so we want to get to the 'cluster' index, being level 1
            for clust in topic_cluster_subset.index.get_level_values(level=1):
                # Skip noise
                if clust != -1:
                    lower_bound = round(topic_cluster_subset.loc[tpc, clust].min_freq, 3)
                    upper_bound = round(topic_cluster_subset.loc[tpc, clust].max_freq, 3)
                    if ((meas >= lower_bound) and (meas <= upper_bound)):
                        tp_hr += 1
                        break
        test_project_meas_hit_rate.append(round(tp_hr/len(list(test_proj_meas.loc[tp].med_freq)), 3))
        test_project_hit_list.append(round(tp_hr/len(list(test_proj_meas.loc[tp].med_freq)), 3))
        # Stats for individual test projects
        print(f'Number of measurements: {len(test_proj_meas.loc[tp].med_freq)}')
        print(f'Hits: {tp_hr}')
        print(f'Hit rate: {round(tp_hr/len(list(test_proj_meas.loc[tp].med_freq)), 3)}')
        print('')

        # Increment test_project_hits if at least one measurement in the project matched
        if (tp_hr > 0):
            test_project_hits +=1
    print('=========================================\n')

print(f'Total number of clusters across topics: {total_num_clusters}')
print(f'Number of test projects with at least one measurement match: {test_project_hits}')
print(f'Ratio of test project hits to number of test projects: {round(test_project_hits/test_texts.shape[0], 4)}')
print(f'Average hit rate per project: {round(np.mean(test_project_hit_list), 4)}')
print(f'Standard Deviation of hit rate per project: {round(np.std(test_project_hit_list), 4)}')

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Spectral Results for topic 0
Number of projects in topic: 26
Total number of measurements: 125
Estimated number of noise measurements: 4.0
Noise proportion: 0.032
Signal proportion: 0.968

Topic 0 cluster width stats:
count    11.0000
mean     11.6059
std      15.1723
min       1.2550
25%       2.7625
50%       5.9850
75%      13.0075
max      52.2800
dtype: float64

Cluster data frame for topic 0
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
0      8        216.860   269.140          51        6.0  52.280
       7         86.845   110.895          24        3.0  24.050
       9        450.495   466.225          19        8.0  15.730
       5        244.245   254.530          11        6.0  10.285
       1        175.765   182.000           3        5.0   6.235
       0        345.945   351.930           4        7.0   5.985
      -1        338.130   342.875           4        7.0   4.745
       2        164.165   168.005           3        5.0   3.840
       4        144.915   146.600           2        4.0   1.685
       6        133.295   134.870           2        4.0   1.575
       3        329.325   330.580           2        7.0   1.255

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 0
Hit rate: 0.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 1
Hit rate: 0.25

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 3
Hit rate: 0.75

=========================================

Spectral Results for topic 1
Number of projects in topic: 39
Total number of measurements: 209
Estimated number of noise measurements: 6.0
Noise proportion: 0.029
Signal proportion: 0.971

Topic 1 cluster width stats:
count    12.0000
mean     14.3704
std      16.1421
min       1.3350
25%       2.2650
50%       4.4475
75%      26.8425
max      49.9900
dtype: float64

Cluster data frame for topic 1
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
1      8        223.915   273.905          44        6.0  49.990
       9        329.325   361.900          70        7.0  32.575
      -1        129.175   156.070           6        4.0  26.895
       6         88.465   115.290          38        3.0  26.825
       10       477.450   494.080          28        8.0  16.630
       0        674.025   678.860           2        9.0   4.835
       3        212.015   216.075           4        6.0   4.060
       7        140.905   144.185           6        4.0   3.280
       1        691.480   693.900           2        9.0   2.420
       2        184.845   186.645           2        5.0   1.800
       4        172.855   174.655           2        5.0   1.800
       5        219.580   220.915           5        6.0   1.335

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 1
Hit rate: 0.333

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 14
Hits: 10
Hit rate: 0.714

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 4
Hit rate: 0.8

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

=========================================

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\base.py:1389: ConvergenceWarning:

Number of distinct clusters (4) found smaller than n_clusters (8). Possibly due to duplicate points in X.

Spectral Results for topic 2
Number of projects in topic: 64
Total number of measurements: 260
Estimated number of noise measurements: 8.0
Noise proportion: 0.031
Signal proportion: 0.969
BAND OVERLAP

Topic 2 cluster width stats:
count     10.0000
mean      31.4185
std       61.3406
min        0.0000
25%        4.2887
50%        6.4850
75%       26.4550
max      201.4950
dtype: float64

Cluster data frame for topic 2
               min_freq  max_freq  count_freq  band_mode    width
topic cluster
2     -1        489.790   691.285           8        8.5  201.495
       3        293.875   337.100          51        7.0   43.225
       2        214.965   245.815          41        6.0   30.850
       7         93.250   106.520          25        3.0   13.270
       1         85.355    92.270          19        3.0    6.915
       8        230.290   236.345          41        6.0    6.055
       4        109.765   115.280          17        3.0    5.515
       5        256.315   260.195          15        6.0    3.880
       6        342.845   345.825          42        7.0    2.980
       0        477.540   477.540           1        8.0    0.000

Ratio of recommended clusters to total clusters: 0.9
Number of measurements: 8
Hits: 5
Hit rate: 0.625

Ratio of recommended clusters to total clusters: 0.9
Number of measurements: 14
Hits: 14
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9
Number of measurements: 12
Hits: 11
Hit rate: 0.917

Ratio of recommended clusters to total clusters: 0.9
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9
Number of measurements: 14
Hits: 11
Hit rate: 0.786

Ratio of recommended clusters to total clusters: 0.9
Number of measurements: 26
Hits: 14
Hit rate: 0.538

Ratio of recommended clusters to total clusters: 0.9
Number of measurements: 8
Hits: 2
Hit rate: 0.25

Ratio of recommended clusters to total clusters: 0.9
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9
Number of measurements: 16
Hits: 16
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9
Number of measurements: 2
Hits: 1
Hit rate: 0.5

=========================================

Spectral Results for topic 3
Number of projects in topic: 35
Total number of measurements: 74
Estimated number of noise measurements: 2.0
Noise proportion: 0.027
Signal proportion: 0.973

Topic 3 cluster width stats:
count    10.0000
mean      3.7115
std       3.8643
min       0.0100
25%       2.0338
50%       2.3675
75%       4.8162
max      13.3550
dtype: float64

Cluster data frame for topic 3
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
3      6        218.135   231.490          29        6.0  13.355
       5        109.775   115.160           5        3.0   5.385
       8        340.925   345.815          12        7.0   4.890
       7         96.410   101.005           7        3.0   4.595
       3        215.095   217.490           6        6.0   2.395
       0         86.765    89.105           3        3.0   2.340
       4        355.090   357.225           6        7.0   2.135
      -1        328.880   330.880           2        7.0   2.000
       1        227.095   227.105           2        6.0   0.010
       2        213.095   213.105           2        6.0   0.010

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 5
Hit rate: 0.833

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 0
Hit rate: 0.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

=========================================

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Spectral Results for topic 4
Number of projects in topic: 48
Total number of measurements: 293
Estimated number of noise measurements: 4.0
Noise proportion: 0.014
Signal proportion: 0.986

Topic 4 cluster width stats:
count    10.0000
mean      8.5830
std      11.6531
min       1.2650
25%       1.8637
50%       2.5500
75%       8.3562
max      30.2400
dtype: float64

Cluster data frame for topic 4
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
4      7         85.025   115.265         147        3.0  30.240
       8        215.880   246.005         116        6.0  30.125
       2        250.205   260.130           6        6.0   9.925
      -1        342.425   346.075           4        7.0   3.650
       5        327.260   330.125           6        7.0   2.865
       6        153.740   155.975           4        4.0   2.235
       1        202.025   204.050           2        5.0   2.025
       0        146.735   148.545           2        4.0   1.810
       4        141.885   143.575           4        4.0   1.690
       3        135.425   136.690           2        4.0   1.265

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 20
Hits: 20
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 20
Hits: 20
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 13
Hits: 13
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

=========================================

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\base.py:1389: ConvergenceWarning:

Number of distinct clusters (4) found smaller than n_clusters (8). Possibly due to duplicate points in X.

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Spectral Results for topic 5
Number of projects in topic: 39
Total number of measurements: 291
Estimated number of noise measurements: 5.0
Noise proportion: 0.017
Signal proportion: 0.983
BAND OVERLAP

Topic 5 cluster width stats:
count      8.0000
mean      62.0538
std      101.2470
min        0.0000
25%        0.0000
50%       29.1375
75%       63.2837
max      302.4800
dtype: float64

Cluster data frame for topic 5
               min_freq  max_freq  count_freq  band_mode    width
topic cluster
5     -1        160.605   463.085           5        5.6  302.480
       6        277.745   354.690          18        7.0   76.945
       5        215.225   273.955         119        6.0   58.730
       3         85.250   114.705         101        3.0   29.455
       4        133.395   162.215          45        4.0   28.820
       1        661.220   661.220           1        9.0    0.000
       0        647.555   647.555           1        9.0    0.000
       2         97.405    97.405           1        3.0    0.000

Ratio of recommended clusters to total clusters: 0.875
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.875
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.875
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.875
Number of measurements: 10
Hits: 10
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.875
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.875
Number of measurements: 3
Hits: 3
Hit rate: 1.0

=========================================

Spectral Results for topic 6
Number of projects in topic: 86
Total number of measurements: 354
Estimated number of noise measurements: 90.0
Noise proportion: 0.254
Signal proportion: 0.746

Topic 6 cluster width stats:
count     8.0000
mean     10.1838
std       5.2274
min       3.2900
25%       7.3237
50%       9.5550
75%      11.7238
max      20.9600
dtype: float64

Cluster data frame for topic 6
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
6      3         84.540   105.500          26        3.0  20.960
       2        239.595   251.525          26        6.0  11.930
       6        213.095   224.750         118        6.0  11.655
       0        254.825   265.885          20        6.0  11.060
      -1        227.095   235.145          90        6.0   8.050
       5        342.365   349.750          39        7.0   7.385
       1        330.615   337.755          14        7.0   7.140
       4        353.705   356.995          21        7.0   3.290

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 3
Hit rate: 0.5

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 2
Hit rate: 0.667

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 0
Hit rate: 0.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 1
Hit rate: 0.333

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 2
Hit rate: 0.667

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

=========================================

Spectral Results for topic 7
Number of projects in topic: 30
Total number of measurements: 143
Estimated number of noise measurements: 1.0
Noise proportion: 0.007
Signal proportion: 0.993

Topic 7 cluster width stats:
count    13.0000
mean     12.2123
std      12.8093
min       0.0000
25%       3.2550
50%       6.1300
75%      16.7850
max      37.9250
dtype: float64

Cluster data frame for topic 7
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
7      8        165.480   203.405          25        5.0  37.925
       6         84.205   115.330          49        3.0  31.125
       9        218.465   247.435           7        6.0  28.970
       3        319.620   336.405          10        7.0  16.785
       11       416.160   431.780          22        8.0  15.620
       10       340.800   347.320          11        7.0   6.520
       0        261.725   267.855           2        6.0   6.130
       7        149.595   154.345           6        4.0   4.750
       5        352.800   356.730           4        7.0   3.930
       1        647.685   650.940           2        9.0   3.255
       4        310.995   312.870           2        7.0   1.875
       2        137.470   139.345           2        4.0   1.875
      -1        661.545   661.545           1        9.0   0.000

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 5
Hit rate: 0.833

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 2
Hit rate: 0.167

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 4
Hit rate: 0.5

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 2
Hit rate: 0.5

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 4
Hit rate: 0.8

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 18
Hits: 4
Hit rate: 0.222

=========================================

Spectral Results for topic 8
Number of projects in topic: 28
Total number of measurements: 176
Estimated number of noise measurements: 2.0
Noise proportion: 0.011
Signal proportion: 0.989

Topic 8 cluster width stats:
count     7.0000
mean     43.4000
std      34.7197
min      10.2000
25%      18.5075
50%      25.2200
75%      67.8050
max      95.7550
dtype: float64

Cluster data frame for topic 8
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
8      3        276.875   372.630          57        7.0  95.755
       4        391.070   476.585          11        8.0  85.515
       2        217.435   267.530          74        6.0  50.095
       0         85.025   110.245          16        3.0  25.220
       5        878.230   897.500           8       10.0  19.270
       1        131.690   149.435           8        4.0  17.745
      -1        183.305   193.505           2        5.0  10.200

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 9
Hits: 9
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 9
Hit rate: 0.75

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 1
Hit rate: 0.5

=========================================

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\base.py:1389: ConvergenceWarning:

Number of distinct clusters (2) found smaller than n_clusters (8). Possibly due to duplicate points in X.

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Spectral Results for topic 9
Number of projects in topic: 75
Total number of measurements: 414
Estimated number of noise measurements: 12.0
Noise proportion: 0.029
Signal proportion: 0.971
BAND OVERLAP

Topic 9 cluster width stats:
count     11.0000
mean      61.5495
std      147.9414
min        1.5800
25%        2.5900
50%        4.5400
75%       41.4300
max      502.9950
dtype: float64

Cluster data frame for topic 9
               min_freq  max_freq  count_freq  band_mode    width
topic cluster
9     -1        128.995   631.990          12        7.0  502.995
       9        299.680   359.135         145        7.0   59.455
       8        214.795   268.605         189        6.0   53.810
       7         85.710   114.760          49        3.0   29.050
       5        483.990   498.190           6        8.0   14.200
       0        708.800   713.340           2        9.0    4.540
       3        474.390   478.625           3        8.0    4.235
       1        438.390   440.990           2        8.0    2.600
       4        691.470   694.050           2        9.0    2.580
       2        321.395   323.395           2        7.0    2.000
       6        287.885   289.465           2        7.0    1.580

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 17
Hits: 17
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 9
Hits: 9
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 13
Hits: 13
Hit rate: 1.0

=========================================

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Spectral Results for topic 10
Number of projects in topic: 202
Total number of measurements: 1234
Estimated number of noise measurements: 8.0
Noise proportion: 0.006
Signal proportion: 0.994
BAND OVERLAP

Topic 10 cluster width stats:
count     13.0000
mean      59.2881
std      135.9270
min        3.3100
25%        5.8950
50%       15.2900
75%       34.4600
max      504.0100
dtype: float64

Cluster data frame for topic 10
               min_freq  max_freq  count_freq  band_mode    width
topic cluster
10    -1        177.335   681.345           8      6.875  504.010
       9        277.000   372.665         149      7.000   95.665
       8        212.190   247.215         436      6.000   35.025
       11       127.505   161.965          37      4.000   34.460
       6         85.010   115.270         470      3.000   30.260
       5        250.520   271.265          86      6.000   20.745
       1        186.455   201.745          13      5.000   15.290
       10        37.595    48.025           8      1.000   10.430
       4        866.385   872.285           4     10.000    5.900
       0        850.320   856.215           4     10.000    5.895
       3        301.810   307.415           7      7.000    5.605
       7        204.975   209.125           5      5.000    4.150
       2        165.345   168.655           7      5.000    3.310

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 14
Hits: 14
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 8
Hits: 6
Hit rate: 0.75

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 7
Hits: 7
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 24
Hits: 24
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 14
Hits: 14
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 15
Hits: 15
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 16
Hits: 16
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 11
Hits: 11
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 19
Hits: 19
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 13
Hits: 13
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 7
Hits: 7
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 14
Hits: 12
Hit rate: 0.857

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 11
Hits: 11
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 9
Hits: 9
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 14
Hits: 14
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 4
Hits: 2
Hit rate: 0.5

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 1
Hits: 0
Hit rate: 0.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 20
Hits: 15
Hit rate: 0.75

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 8
Hits: 6
Hit rate: 0.75

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 12
Hits: 11
Hit rate: 0.917

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 14
Hits: 14
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 10
Hits: 9
Hit rate: 0.9

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 23
Hits: 23
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 13
Hits: 10
Hit rate: 0.769

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 4
Hits: 4
Hit rate: 1.0

=========================================

Spectral Results for topic 11
Number of projects in topic: 12
Total number of measurements: 36
Estimated number of noise measurements: 3.0
Noise proportion: 0.083
Signal proportion: 0.917

Topic 11 cluster width stats:
count    10.0000
mean      3.5565
std       4.2989
min       0.2050
25%       1.8925
50%       1.9200
75%       2.0000
max      14.6500
dtype: float64

Cluster data frame for topic 11
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
11     7        357.980   372.630           8        7.0  14.650
       8        477.865   485.085           8        8.0   7.220
       1        227.075   229.075           2        6.0   2.000
       0        213.075   215.075           2        6.0   2.000
       5        495.255   497.195           4        8.0   1.940
       6        345.815   347.715           3        7.0   1.900
       4        333.815   335.715           2        7.0   1.900
       2        469.435   471.325           2        8.0   1.890
       3        489.885   491.745           2        8.0   1.860
      -1        113.470   113.675           3        3.0   0.205

=========================================

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\base.py:1389: ConvergenceWarning:

Number of distinct clusters (2) found smaller than n_clusters (8). Possibly due to duplicate points in X.

Spectral Results for topic 12
Number of projects in topic: 130
Total number of measurements: 838
Estimated number of noise measurements: 1.0
Noise proportion: 0.001
Signal proportion: 0.999

Topic 12 cluster width stats:
count     9.0000
mean     35.0244
std      25.4761
min       0.0000
25%      19.1250
50%      32.3950
75%      35.5350
max      87.1550
dtype: float64

Cluster data frame for topic 12
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
12     4        277.010   364.165         114        7.0  87.155
       3        212.145   272.820         239        6.0  60.675
       5        456.630   492.165          74        8.0  35.535
       1        126.035   158.505          38        4.0  32.470
       2        177.490   209.885          12        5.0  32.395
       0         85.120   115.275         343        3.0  30.155
       6        672.350   691.475           9        9.0  19.125
       7        805.960   823.670           8       10.0  17.710
      -1        713.350   713.350           1        9.0   0.000

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 3
Hit rate: 0.75

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 15
Hits: 15
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 6
Hit rate: 0.75

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 9
Hits: 9
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 11
Hits: 11
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 20
Hits: 20
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 7
Hits: 7
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 18
Hits: 18
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 0
Hit rate: 0.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 16
Hits: 16
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 15
Hits: 15
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 7
Hits: 7
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 0
Hit rate: 0.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 14
Hits: 14
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 10
Hits: 10
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 1
Hit rate: 0.5

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 10
Hits: 10
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 3
Hit rate: 0.6

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 17
Hits: 17
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 20
Hits: 20
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 7
Hit rate: 0.875

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 13
Hits: 13
Hit rate: 1.0

=========================================

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Spectral Results for topic 13
Number of projects in topic: 114
Total number of measurements: 631
Estimated number of noise measurements: 4.0
Noise proportion: 0.006
Signal proportion: 0.994

Topic 13 cluster width stats:
count    13.0000
mean     17.0288
std      16.7249
min       1.5000
25%       1.8700
50%      10.2100
75%      28.6950
max      57.7900
dtype: float64

Cluster data frame for topic 13
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
13     9        216.115   273.905         172        6.0  57.790
       7         84.565   115.270         224        3.0  30.705
       6        682.615   711.585          20        9.0  28.970
       10       336.600   365.295          52        7.0  28.695
       8        136.680   161.990          81        4.0  25.310
       11       474.735   492.280          46        8.0  17.545
       2        458.760   468.970           6        8.0  10.210
       5        126.100   134.365          14        4.0   8.265
       1        302.400   309.340           3        7.0   6.940
       0        294.395   296.265           2        7.0   1.870
       3        282.395   284.265           2        7.0   1.870
      -1        203.340   205.045           4        5.0   1.705
       4        330.410   331.910           5        7.0   1.500

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 2
Hit rate: 0.667

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 6
Hit rate: 0.75

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 2
Hit rate: 0.5

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 4
Hit rate: 0.5

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 7
Hits: 7
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 16
Hits: 16
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 16
Hits: 16
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 11
Hit rate: 0.917

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 1
Hit rate: 0.5

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 10
Hits: 9
Hit rate: 0.9

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 7
Hits: 7
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 0
Hit rate: 0.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 0
Hit rate: 0.0

=========================================

Spectral Results for topic 14
Number of projects in topic: 20
Total number of measurements: 95
Estimated number of noise measurements: 2.0
Noise proportion: 0.021
Signal proportion: 0.979

Topic 14 cluster width stats:
count     9.0000
mean     12.1478
std      27.2635
min       0.0000
25%       1.6400
50%       2.2200
75%       7.4000
max      84.4600
dtype: float64

Cluster data frame for topic 14
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
14     7        275.840   360.300          62        7.0  84.460
       4         95.785   103.725          10        3.0   7.940
       2        212.995   220.395           5        6.0   7.400
       0        226.305   229.700           3        6.0   3.395
       6        107.895   110.115           8        3.0   2.220
      -1         88.275    90.275           2        3.0   2.000
       1        261.260   262.900           2        6.0   1.640
       3        235.785   236.060           2        6.0   0.275
       5        223.305   223.305           1        6.0   0.000

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 10
Hits: 1
Hit rate: 0.1

=========================================

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Spectral Results for topic 15
Number of projects in topic: 43
Total number of measurements: 157
Estimated number of noise measurements: 2.0
Noise proportion: 0.013
Signal proportion: 0.987

Topic 15 cluster width stats:
count    11.0000
mean     13.5514
std      18.0260
min       0.9950
25%       2.7700
50%       6.3300
75%      15.2950
max      59.0750
dtype: float64

Cluster data frame for topic 15
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
15     7        213.765   272.840          39        6.0  59.075
       8        332.255   364.625          54        7.0  32.370
       9        128.315   151.295          27        4.0  22.980
       6        172.690   180.300           6        5.0   7.610
       0        282.440   289.720           6        7.0   7.280
       3        295.390   301.720           5        7.0   6.330
       5        239.125   244.940           6        6.0   5.815
       4        230.160   233.760           8        6.0   3.600
       1        101.065   103.005           2        3.0   1.940
       2        157.195   158.265           2        4.0   1.070
      -1        191.290   192.285           2        5.0   0.995

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 8
Hit rate: 0.667

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 19
Hits: 17
Hit rate: 0.895

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 18
Hits: 3
Hit rate: 0.167

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

=========================================

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Spectral Results for topic 16
Number of projects in topic: 54
Total number of measurements: 323
Estimated number of noise measurements: 28.0
Noise proportion: 0.087
Signal proportion: 0.913

Topic 16 cluster width stats:
count    13.0000
mean     15.5015
std      15.4167
min       1.7900
25%       5.5800
50%      11.2950
75%      16.7400
max      56.8250
dtype: float64

Cluster data frame for topic 16
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
16     9        217.090   273.915          76        6.0  56.825
       6         85.015   114.890         100        3.0  29.875
       11       675.695   705.020          20        9.0  29.325
       10       330.590   347.330          57        7.0  16.740
      -1        245.305   259.255          28        6.0  13.950
       7        143.950   157.890           8        4.0  13.940
       4        885.470   896.765           8       10.0  11.295
       8        183.300   193.995           6        5.0  10.695
       1        901.170   906.795           4       10.0   5.625
       2        874.815   880.395           4       10.0   5.580
       3        658.010   661.075           2        9.0   3.065
       0        643.620   646.435           2        9.0   2.815
       5        352.605   354.395           8        7.0   1.790

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 15
Hits: 13
Hit rate: 0.867

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 16
Hits: 12
Hit rate: 0.75

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 24
Hits: 23
Hit rate: 0.958

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

=========================================

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Spectral Results for topic 17
Number of projects in topic: 94
Total number of measurements: 479
Estimated number of noise measurements: 1.0
Noise proportion: 0.002
Signal proportion: 0.998

Topic 17 cluster width stats:
count    13.0000
mean     21.6323
std      25.9399
min       0.0000
25%       1.8200
50%       8.0650
75%      33.0900
max      83.3500
dtype: float64

Cluster data frame for topic 17
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
17     11       398.935   482.285          28        8.0  83.350
       10       289.005   345.755          25        7.0  56.750
       9        217.995   258.720          72        6.0  40.725
       8        128.640   161.730          73        4.0  33.090
       7         85.045   115.125         249        3.0  30.080
       3        349.635   363.500           9        7.0  13.865
       6        262.695   270.760           9        6.0   8.065
       1        428.605   434.615           4        8.0   6.010
       4        277.935   283.580           4        7.0   5.645
       2        493.025   494.845           2        8.0   1.820
       5        417.165   418.985           2        8.0   1.820
      -1        682.220   682.220           1        9.0   0.000
       0        315.775   315.775           1        7.0   0.000

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 14
Hits: 14
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 7
Hit rate: 0.875

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 20
Hits: 19
Hit rate: 0.95

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 7
Hit rate: 0.875

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 7
Hit rate: 0.875

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 10
Hits: 10
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 3
Hit rate: 0.75

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 3
Hit rate: 0.5

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 7
Hit rate: 0.875

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 16
Hits: 16
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 21
Hits: 20
Hit rate: 0.952

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 15
Hits: 15
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 6
Hit rate: 0.75

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 7
Hit rate: 0.875

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

=========================================

Spectral Results for topic 18
Number of projects in topic: 59
Total number of measurements: 269
Estimated number of noise measurements: 4.0
Noise proportion: 0.015
Signal proportion: 0.985

Topic 18 cluster width stats:
count    10.0000
mean     11.4475
std      13.2795
min       1.7000
25%       2.9538
50%       3.9625
75%      18.0438
max      37.1400
dtype: float64

Cluster data frame for topic 18
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
18     8        224.865   262.005          72        6.0  37.140
       7         84.530   115.180         125        3.0  30.650
       6        330.305   351.860          32        7.0  21.555
       0        214.375   221.885          17        6.0   7.510
       2        355.295   360.160           5        7.0   4.865
       3        305.365   308.425           4        7.0   3.060
       4        369.900   372.865           4        7.0   2.965
      -1        150.510   153.460           4        4.0   2.950
       5        139.760   141.840           4        4.0   2.080
       1        317.905   319.605           2        7.0   1.700

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

=========================================

Spectral Results for topic 19
Number of projects in topic: 101
Total number of measurements: 363
Estimated number of noise measurements: 2.0
Noise proportion: 0.006
Signal proportion: 0.994

Topic 19 cluster width stats:
count    11.0000
mean      9.1932
std      13.6294
min       1.6700
25%       2.0300
50%       3.5000
75%       5.6950
max      43.0200
dtype: float64

Cluster data frame for topic 19
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
19     7         212.53   255.550         170        6.0  43.020
       8         329.32   357.895         146        7.0  28.575
       4          90.60    97.615           8        3.0   7.015
       9         489.74   494.115          17        8.0   4.375
       6         106.39   110.200           7        3.0   3.810
      -1         674.01   677.510           2        9.0   3.500
       1         688.27   691.470           2        9.0   3.200
       5         102.60   104.700           5        3.0   2.100
       0         410.05   412.010           2        8.0   1.960
       2         398.05   399.950           2        8.0   1.900
       3         265.88   267.550           2        6.0   1.670

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 10
Hits: 10
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 1
Hit rate: 0.5

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 0
Hit rate: 0.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 2
Hit rate: 0.5

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 0
Hit rate: 0.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 24
Hits: 24
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 5
Hit rate: 0.417

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 11
Hits: 11
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 0
Hit rate: 0.0

=========================================

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Spectral Results for topic 20
Number of projects in topic: 55
Total number of measurements: 249
Estimated number of noise measurements: 3.0
Noise proportion: 0.012
Signal proportion: 0.988

Topic 20 cluster width stats:
count     9.0000
mean     10.1644
std      12.5365
min       1.6850
25%       2.2500
50%       4.3700
75%       7.3050
max      33.3250
dtype: float64

Cluster data frame for topic 20
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
20     7        213.075   246.400         140        6.0  33.325
       6         84.745   115.275          62        3.0  30.530
       4        343.130   350.435          15        7.0   7.305
       0        331.130   338.375           6        7.0   7.245
       3        137.985   142.355           8        4.0   4.370
       2        355.220   357.990           7        7.0   2.770
      -1        259.005   261.255           3        6.0   2.250
       1        150.025   152.025           4        4.0   2.000
       5        128.545   130.230           4        4.0   1.685

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 2
Hit rate: 0.25

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 24
Hits: 24
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 3
Hit rate: 0.5

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 16
Hits: 16
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 2
Hit rate: 0.5

=========================================

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Spectral Results for topic 21
Number of projects in topic: 101
Total number of measurements: 614
Estimated number of noise measurements: 3.0
Noise proportion: 0.005
Signal proportion: 0.995

Topic 21 cluster width stats:
count    12.0000
mean     12.6413
std      10.6391
min       1.7200
25%       4.3712
50%       7.0875
75%      20.7262
max      31.3800
dtype: float64

Cluster data frame for topic 21
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
21     9        341.485   372.865          85        7.0  31.380
       3        239.755   267.565          44        6.0  27.810
       8        213.010   236.455         317        6.0  23.445
       5         85.680   105.500          70        3.0  19.820
       10       138.180   154.885          17        4.0  16.705
       4        329.320   337.390          25        7.0   8.070
       7        109.170   115.275          33        3.0   6.105
       0        685.430   691.465           2        9.0   6.035
       1        477.490   481.905           7        8.0   4.415
       6        489.740   493.980           6        8.0   4.240
       2        185.440   187.390           5        5.0   1.950
      -1        172.670   174.390           3        5.0   1.720

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 11
Hits: 11
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 10
Hits: 10
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 14
Hits: 14
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 5
Hit rate: 0.833

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 7
Hits: 7
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 11
Hits: 6
Hit rate: 0.545

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 11
Hits: 11
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 15
Hits: 15
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 0
Hit rate: 0.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 7
Hits: 7
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 3
Hit rate: 0.5

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 25
Hits: 25
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 14
Hits: 14
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 26
Hits: 26
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

=========================================

Spectral Results for topic 22
Number of projects in topic: 31
Total number of measurements: 143
Estimated number of noise measurements: 4.0
Noise proportion: 0.028
Signal proportion: 0.972

Topic 22 cluster width stats:
count    10.0000
mean      8.5005
std       9.9917
min       0.0050
25%       1.9313
50%       4.6125
75%      10.3375
max      30.8750
dtype: float64

Cluster data frame for topic 22
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
22     7         84.430   115.305          62        3.0  30.875
       0        338.895   359.115          28        7.0  20.220
       3        225.580   236.130          11        6.0  10.550
       6        240.255   249.955          12        6.0   9.700
       5         97.980   103.760           9        3.0   5.780
       8        458.610   462.055          10        8.0   3.445
       2        218.285   220.460           3        6.0   2.175
       1        257.950   259.800           2        6.0   1.850
      -1        153.810   154.215           4        4.0   0.405
       4        144.610   144.615           2        4.0   0.005

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 20
Hits: 0
Hit rate: 0.0

=========================================

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Spectral Results for topic 23
Number of projects in topic: 52
Total number of measurements: 245
Estimated number of noise measurements: 12.0
Noise proportion: 0.049
Signal proportion: 0.951
BAND OVERLAP

Topic 23 cluster width stats:
count     13.0000
mean      37.5542
std       91.0637
min        0.0000
25%        1.8750
50%        3.0200
75%       15.2050
max      330.9700
dtype: float64

Cluster data frame for topic 23
               min_freq  max_freq  count_freq  band_mode    width
topic cluster
23    -1        492.150   823.120          12        9.0  330.970
       11       279.505   356.725          38        7.0   77.220
       10       216.110   261.250         141        6.0   45.140
       8        140.300   155.505          14        4.0   15.205
       4         90.500    96.740           7        3.0    6.240
       9        174.950   178.200          12        5.0    3.250
       5        806.290   809.310           4       10.0    3.020
       1        267.540   269.935           2        6.0    2.395
       6        291.895   293.915           4        7.0    2.020
       2        102.500   104.375           2        3.0    1.875
       7        108.735   109.270           6        3.0    0.535
       3        337.065   337.400           2        7.0    0.335
       0        482.125   482.125           1        8.0    0.000

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 3
Hit rate: 0.75

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 9
Hits: 9
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 4
Hit rate: 0.667

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 0
Hit rate: 0.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 0
Hit rate: 0.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

=========================================

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Spectral Results for topic 24
Number of projects in topic: 128
Total number of measurements: 799
Estimated number of noise measurements: 2.0
Noise proportion: 0.003
Signal proportion: 0.997

Topic 24 cluster width stats:
count    12.0000
mean     14.7412
std      23.5592
min       1.1950
25%       1.8975
50%       5.7200
75%      15.1025
max      84.0550
dtype: float64

Cluster data frame for topic 24
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
24     9        275.845   359.900         102        7.0  84.055
       6         85.450   115.320         341        3.0  29.870
       8        215.200   234.975         262        6.0  19.775
       7        134.010   147.555          12        4.0  13.545
       4        238.220   248.000          25        6.0   9.780
       10       253.960   261.275          20        6.0   7.315
       3        362.565   366.690          11        7.0   4.125
       0        370.500   372.670           5        7.0   2.170
       5        265.875   267.810          11        6.0   1.935
       1        154.215   156.000           3        4.0   1.785
      -1        459.700   461.045           2        8.0   1.345
       2        270.775   271.970           5        6.0   1.195

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 20
Hits: 19
Hit rate: 0.95

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 4
Hit rate: 0.667

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 9
Hits: 9
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 0
Hit rate: 0.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 7
Hits: 7
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 19
Hits: 19
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 9
Hits: 9
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 15
Hits: 9
Hit rate: 0.6

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 7
Hits: 7
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 11
Hits: 11
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 9
Hits: 9
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 3
Hit rate: 0.75

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 21
Hits: 21
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 17
Hits: 17
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 18
Hits: 18
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

=========================================

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Spectral Results for topic 25
Number of projects in topic: 28
Total number of measurements: 139
Estimated number of noise measurements: 2.0
Noise proportion: 0.014
Signal proportion: 0.986

Topic 25 cluster width stats:
count    11.0000
mean      8.7900
std       8.2555
min       1.8850
25%       1.9575
50%       6.1800
75%      12.3425
max      26.8300
dtype: float64

Cluster data frame for topic 25
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
25     8        217.040   243.870          50        6.0  26.830
       6         96.165   115.290          38        3.0  19.125
       7        132.550   146.925           8        4.0  14.375
       9        344.975   355.285          19        7.0  10.310
       2         85.495    93.285           6        3.0   7.790
       1        152.935   159.115           4        4.0   6.180
       5        100.905   105.285           6        3.0   4.380
      -1        304.120   306.095           2        7.0   1.975
       0        297.580   299.520           2        7.0   1.940
       4        285.515   287.415           2        7.0   1.900
       3        316.170   318.055           2        7.0   1.885

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 17
Hits: 11
Hit rate: 0.647

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 7
Hits: 7
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 17
Hits: 17
Hit rate: 1.0

=========================================

Spectral Results for topic 26
Number of projects in topic: 28
Total number of measurements: 116
Estimated number of noise measurements: 4.0
Noise proportion: 0.034
Signal proportion: 0.966

Topic 26 cluster width stats:
count    10.0000
mean     13.3335
std      14.2809
min       0.1250
25%       2.8537
50%       9.4350
75%      13.7900
max      41.0750
dtype: float64

Cluster data frame for topic 26
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
26     8        227.060   268.135          41        6.0  41.075
       5        320.630   357.205          14        7.0  36.575
       6         85.275    99.270          22        3.0  13.995
       7        133.795   146.970           8        4.0  13.175
       1        105.290   114.950           6        3.0   9.660
       0        212.050   221.260           7        6.0   9.210
       4        339.470   345.305           8        7.0   5.835
       2        489.600   491.460           4        8.0   1.860
      -1        477.590   479.415           4        8.0   1.825
       3        483.745   483.870           2        8.0   0.125

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 9
Hits: 8
Hit rate: 0.889

=========================================

Spectral Results for topic 27
Number of projects in topic: 25
Total number of measurements: 120
Estimated number of noise measurements: 2.0
Noise proportion: 0.017
Signal proportion: 0.983

Topic 27 cluster width stats:
count    11.0000
mean      6.0768
std       7.0962
min       0.0000
25%       1.1750
50%       3.5250
75%       9.4500
max      21.0000
dtype: float64

Cluster data frame for topic 27
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
27     8        213.075   234.075          48        6.0  21.000
       9        349.425   363.785          19        7.0  14.360
       7         86.255   100.275          30        3.0  14.020
       1        352.630   357.510           4        7.0   4.880
       2        340.590   345.465           5        7.0   4.875
       6        153.135   156.660           5        4.0   3.525
       3        612.455   614.220           2        9.0   1.765
       5        145.560   146.970           2        4.0   1.410
      -1        625.010   625.950           2        9.0   0.940
       4         90.910    90.980           2        3.0   0.070
       0        136.465   136.465           1        4.0   0.000

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 0
Hit rate: 0.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 10
Hits: 10
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 4
Hit rate: 0.5

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 3
Hit rate: 0.75

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 21
Hits: 21
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 9
Hits: 2
Hit rate: 0.222

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 5
Hit rate: 0.625

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Number of measurements: 10
Hits: 5
Hit rate: 0.5

=========================================

Spectral Results for topic 28
Number of projects in topic: 44
Total number of measurements: 192
Estimated number of noise measurements: 9.0
Noise proportion: 0.047
Signal proportion: 0.953
BAND OVERLAP

Topic 28 cluster width stats:

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

count     11.0000
mean      39.6377
std      102.7105
min        0.0800
25%        2.6300
50%        5.0000
75%       18.0625
max      348.0650
dtype: float64

Cluster data frame for topic 28
               min_freq  max_freq  count_freq  band_mode    width
topic cluster
28    -1        130.710   478.775           9   4.888889  348.065
       7         85.640   114.560          28   3.000000   28.920
       8        212.505   234.630         106   6.000000   22.125
       6        343.935   357.935          14   7.000000   14.000
       4         97.975   104.605          11   3.000000    6.630
       0        690.010   695.010           4   9.000000    5.000
       9        241.985   246.590           6   6.000000    4.605
       2        250.690   253.665           4   6.000000    2.975
       5        265.845   268.130           6   6.000000    2.285
       1        490.775   492.105           2   8.000000    1.330
       3        330.540   330.620           2   7.000000    0.080

Ratio of recommended clusters to total clusters: 0.9090909090909091
Number of measurements: 4
Hits: 3
Hit rate: 0.75

Ratio of recommended clusters to total clusters: 0.9090909090909091
Number of measurements: 4
Hits: 4
Hit rate: 1.0

=========================================

Spectral Results for topic 29
Number of projects in topic: 33
Total number of measurements: 129
Estimated number of noise measurements: 4.0
Noise proportion: 0.031
Signal proportion: 0.969
BAND OVERLAP

Topic 29 cluster width stats:
count      9.0000
mean      34.8789
std       57.8546
min        1.4150
25%        1.8750
50%       14.8050
75%       30.1800
max      181.5200
dtype: float64

Cluster data frame for topic 29
               min_freq  max_freq  count_freq  band_mode    width
topic cluster
29    -1        129.575   311.095           4        5.5  181.520
       7        216.910   271.385          47        6.0   54.475
       6         85.105   115.285          49        3.0   30.180
       4        343.695   369.505           5        7.0   25.810
       0        240.580   255.385          14        6.0   14.805
       2        212.595   214.590           4        6.0    1.995
       3        284.605   286.480           2        7.0    1.875
       1        141.445   143.280           2        4.0    1.835
       5        330.295   331.710           2        7.0    1.415

Ratio of recommended clusters to total clusters: 0.8888888888888888
Number of measurements: 16
Hits: 3
Hit rate: 0.188

Ratio of recommended clusters to total clusters: 0.8888888888888888
Number of measurements: 7
Hits: 7
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.8888888888888888
Number of measurements: 8
Hits: 7
Hit rate: 0.875

Ratio of recommended clusters to total clusters: 0.8888888888888888
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.8888888888888888
Number of measurements: 11
Hits: 11
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.8888888888888888
Number of measurements: 7
Hits: 7
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.8888888888888888

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Number of measurements: 7
Hits: 7
Hit rate: 1.0

=========================================

Spectral Results for topic 30
Number of projects in topic: 27
Total number of measurements: 236
Estimated number of noise measurements: 4.0
Noise proportion: 0.017
Signal proportion: 0.983

Topic 30 cluster width stats:
count     7.0000
mean     29.9829
std      22.8534
min       0.0000
25%      17.7600
50%      25.1300
75%      40.7225
max      67.7850
dtype: float64

Cluster data frame for topic 30
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
30     4        645.525   713.310           6        9.0  67.785
       3        213.120   264.270         143        6.0  51.150
       2        129.665   159.960          43        4.0  30.295
       1         85.895   111.025          31        3.0  25.130
       5        807.515   829.470           8       10.0  21.955
      -1        338.195   351.760           4        7.0  13.565
       0        691.440   691.440           1        9.0   0.000

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 3
Hit rate: 0.75

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 14
Hits: 0
Hit rate: 0.0

=========================================

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\base.py:1389: ConvergenceWarning:

Number of distinct clusters (2) found smaller than n_clusters (8). Possibly due to duplicate points in X.

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\base.py:1389: ConvergenceWarning:

Number of distinct clusters (3) found smaller than n_clusters (8). Possibly due to duplicate points in X.

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Spectral Results for topic 31
Number of projects in topic: 20
Total number of measurements: 135
Estimated number of noise measurements: 4.0
Noise proportion: 0.03
Signal proportion: 0.97

Topic 31 cluster width stats:
count     6.0000
mean     25.6167
std      29.9478
min       0.0000
25%       3.3587
50%      13.6600
75%      46.6750
max      68.7750
dtype: float64

Cluster data frame for topic 31
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
31     4        294.995   363.770          66        7.0  68.775
       3        214.370   271.975          53        6.0  57.605
      -1        477.620   491.505           4        8.0  13.885
       2         88.260   101.695          10        3.0  13.435
       0        186.340   186.340           1        5.0   0.000
       1        176.525   176.525           1        5.0   0.000

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 13
Hits: 3
Hit rate: 0.231

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 4
Hit rate: 0.8

=========================================

Spectral Results for topic 32
Number of projects in topic: 25
Total number of measurements: 151
Estimated number of noise measurements: 4.0
Noise proportion: 0.026
Signal proportion: 0.974

Topic 32 cluster width stats:
count    12.0000
mean     10.8629
std      12.0079
min       0.0050
25%       3.0687
50%       6.0825
75%      14.0087
max      34.6700
dtype: float64

Cluster data frame for topic 32
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
32     7        216.110   250.780          23        6.0  34.670
       8        338.965   372.665          19        7.0  33.700
       5         97.815   114.760          39        3.0  16.945
       6        127.950   140.980          26        4.0  13.030
       10       307.105   316.795           5        7.0   9.690
       1         86.005    93.170           7        3.0   7.165
      -1        689.970   694.970           4        9.0   5.000
       3        325.940   330.580          10        7.0   4.640
       4        356.730   360.155           7        7.0   3.425
       9        265.550   267.550           7        6.0   2.000
       2        396.110   396.195           2        8.0   0.085
       0        364.725   364.730           2        7.0   0.005

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 24
Hits: 21
Hit rate: 0.875

=========================================

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Spectral Results for topic 33
Number of projects in topic: 41
Total number of measurements: 236
Estimated number of noise measurements: 4.0
Noise proportion: 0.017
Signal proportion: 0.983

Topic 33 cluster width stats:
count    13.0000
mean     12.6612
std      14.1438
min       1.6500
25%       3.7350
50%       4.8850
75%      17.9400
max      49.7350
dtype: float64

Cluster data frame for topic 33
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
33     10       212.105   261.840          67        6.0  49.735
       7         85.935   115.270          55        3.0  29.335
       11       340.105   359.295          54        7.0  19.190
       8        127.205   145.145          16        4.0  17.940
       9        166.120   183.310          17        5.0  17.190
       4        290.660   299.845           6        7.0   9.185
       2        305.005   309.890           3        7.0   4.885
       5        150.485   154.895           4        4.0   4.410
      -1        861.065   864.805           4       10.0   3.740
       6        878.385   882.120           4       10.0   3.735
       0        331.950   333.750           2        7.0   1.800
       1        278.590   280.390           2        7.0   1.800
       3        159.765   161.415           2        5.0   1.650

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

=========================================

Spectral Results for topic 34
Number of projects in topic: 27
Total number of measurements: 128
Estimated number of noise measurements: 5.0
Noise proportion: 0.039
Signal proportion: 0.961
BAND OVERLAP

Topic 34 cluster width stats:
count     13.0000
mean      29.1754
std       71.6679
min        0.0100
25%        1.8500
50%        4.2400
75%       19.3000
max      264.4550
dtype: float64

Cluster data frame for topic 34
               min_freq  max_freq  count_freq  band_mode    width
topic cluster
34    -1        126.145   390.600           5        4.8  264.455
       9        223.125   257.000          44        6.0   33.875
       8        172.675   203.410          20        5.0   30.735
       11       607.170   626.470           9        9.0   19.300
       7         99.400   115.280          26        3.0   15.880
       10       320.795   325.125           7        7.0    4.330
       2        332.795   337.035           5        7.0    4.240
       3        292.485   294.360           2        7.0    1.875
       0        304.405   306.275           2        7.0    1.870
       1        138.080   139.930           2        4.0    1.850
       4        219.550   220.390           2        6.0    0.840
       6        177.240   177.260           2        5.0    0.020
       5        193.295   193.305           2        5.0    0.010

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 13
Hits: 7
Hit rate: 0.538

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 5
Hits: 0
Hit rate: 0.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 4
Hits: 0
Hit rate: 0.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 7
Hits: 0
Hit rate: 0.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 17
Hits: 17
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Number of measurements: 14
Hits: 2
Hit rate: 0.143

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9230769230769231
Number of measurements: 4
Hits: 0
Hit rate: 0.0

=========================================

Spectral Results for topic 35
Number of projects in topic: 39
Total number of measurements: 150
Estimated number of noise measurements: 4.0
Noise proportion: 0.027
Signal proportion: 0.973

Topic 35 cluster width stats:
count    12.0000
mean     18.0825
std      25.1384
min       0.0100
25%       1.7800
50%       5.9575
75%      23.7475
max      76.9950
dtype: float64

Cluster data frame for topic 35
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
35     10       279.495   356.490          48        7.0  76.995
       8        160.010   209.980          17        5.0  49.970
       9        216.110   261.030          36        6.0  44.920
       7         97.435   114.125          13        3.0  16.690
       5         85.435    92.475           8        3.0   7.040
       3        241.595   248.500           6        6.0   6.905
      -1        130.885   135.895           4        4.0   5.010
       0        143.000   147.895           4        4.0   4.895
       2        196.005   197.910           4        5.0   1.905
       4        389.675   391.080           4        8.0   1.405
       6        321.215   322.460           4        7.0   1.245
       1        293.885   293.895           2        7.0   0.010

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 17
Hits: 17
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 0
Hit rate: 0.0

=========================================

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\base.py:1389: ConvergenceWarning:

Number of distinct clusters (2) found smaller than n_clusters (8). Possibly due to duplicate points in X.

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Spectral Results for topic 36
Number of projects in topic: 34
Total number of measurements: 185
Estimated number of noise measurements: 2.0
Noise proportion: 0.011
Signal proportion: 0.989

Topic 36 cluster width stats:
count     6.0000
mean     29.3308
std      19.9606
min      10.1750
25%      17.1862
50%      24.0600
75%      33.8062
max      65.7400
dtype: float64

Cluster data frame for topic 36
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
36     4        283.325   349.065          34        7.0  65.740
       3        211.210   247.000          80        6.0  35.790
       0         85.870   113.725          47        3.0  27.855
       1        126.705   146.970          14        4.0  20.265
       2        191.215   207.375           8        5.0  16.160
      -1        164.265   174.440           2        5.0  10.175

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

=========================================

Spectral Results for topic 37
Number of projects in topic: 31
Total number of measurements: 172
Estimated number of noise measurements: 4.0
Noise proportion: 0.023
Signal proportion: 0.977

Topic 37 cluster width stats:
count    10.0000
mean      8.4235
std      13.8236
min       0.9800
25%       1.6838
50%       3.0975
75%       6.7900
max      45.9200
dtype: float64

Cluster data frame for topic 37
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
37     7        217.070   262.990         130        6.0  45.920
       8        337.005   351.740          12        7.0  14.735
       5         94.315   102.100           8        3.0   7.785
       0        170.875   174.680           2        5.0   3.805
       2         85.655    89.285           4        3.0   3.630
       4        106.260   108.825           4        3.0   2.565
       6        112.300   114.100           4        3.0   1.800
       1        225.975   227.620           2        6.0   1.645
       3        362.705   364.075           2        7.0   1.370
      -1        185.615   186.595           4        5.0   0.980

=========================================

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\base.py:1389: ConvergenceWarning:

Number of distinct clusters (2) found smaller than n_clusters (8). Possibly due to duplicate points in X.

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Spectral Results for topic 38
Number of projects in topic: 13
Total number of measurements: 77
Estimated number of noise measurements: 1.0
Noise proportion: 0.013
Signal proportion: 0.987

Topic 38 cluster width stats:
count     6.0000
mean     29.1075
std      20.9682
min       0.0000
25%      15.7338
50%      29.6400
75%      43.8200
max      55.7200
dtype: float64

Cluster data frame for topic 38
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
38     4        316.950   372.670          12        7.0  55.720
       2        163.305   209.265          20        5.0  45.960
       3        225.775   263.175           7        6.0  37.400
       0         85.025   106.905          29        3.0  21.880
       1        131.390   145.075           8        4.0  13.685
      -1        288.870   288.870           1        7.0   0.000

=========================================

Spectral Results for topic 39
Number of projects in topic: 88
Total number of measurements: 759
Estimated number of noise measurements: 6.0
Noise proportion: 0.008
Signal proportion: 0.992
BAND OVERLAP

Topic 39 cluster width stats:
count     13.0000
mean      38.4577
std       65.5923
min        0.0000
25%        4.7800
50%       14.4950
75%       35.6750
max      241.0300
dtype: float64

Cluster data frame for topic 39
               min_freq  max_freq  count_freq  band_mode    width
topic cluster
39    -1        131.615   372.645           6        5.0  241.030
       10       278.600   365.370         237        7.0   86.770
       9        216.380   265.890         244        6.0   49.510
       8        168.795   204.470          37        5.0   35.675
       6         84.730   113.490         139        3.0   28.760
       7        142.900   160.200          60        4.0   17.300
       11       477.680   492.175          14        8.0   14.495
       4        312.410   322.100           8        7.0    9.690
       1        691.990   697.940           2        9.0    5.950
       0        621.130   625.910           3        9.0    4.780
       3        708.775   711.980           2        9.0    3.205
       5        271.970   274.755           6        6.0    2.785
       2        611.540   611.540           1        9.0    0.000

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 4
Hit rate: 0.667

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 7
Hits: 7
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 17
Hits: 17
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 16
Hits: 16
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 13
Hits: 13
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 13
Hits: 13
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 20
Hits: 20
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 10
Hit rate: 0.833

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 18
Hits: 18
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 7
Hits: 4
Hit rate: 0.571

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 9
Hits: 9
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 18
Hits: 18
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 25
Hits: 25
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 20
Hits: 16
Hit rate: 0.8

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 9
Hits: 8
Hit rate: 0.889

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 20
Hits: 19
Hit rate: 0.95

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 10
Hits: 8
Hit rate: 0.8

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 4
Hit rate: 0.8

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 9
Hits: 9
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 15
Hits: 15
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 20
Hits: 20
Hit rate: 1.0

=========================================

Spectral Results for topic 40
Number of projects in topic: 22
Total number of measurements: 85
Estimated number of noise measurements: 3.0
Noise proportion: 0.035
Signal proportion: 0.965
BAND OVERLAP

Topic 40 cluster width stats:
count     11.0000
mean      50.1782
std      125.3798
min        0.0050
25%        1.9125
50%        2.0500
75%       20.1600
max      421.8750
dtype: float64

Cluster data frame for topic 40
               min_freq  max_freq  count_freq  band_mode    width
topic cluster
40    -1         39.175   461.050           3   3.333333  421.875
       9        277.450   355.205          49   7.000000   77.755
       8        164.175   188.495           6   5.000000   24.320
       7         89.940   105.940          11   3.000000   16.000
       0        231.505   234.445           2   6.000000    2.940
       1        247.005   249.055           2   6.000000    2.050
       6         36.080    38.020           3   1.000000    1.940
       5         41.170    43.105           3   1.000000    1.935
       3        198.605   200.495           2   5.000000    1.890
       2         99.985   101.235           2   3.000000    1.250
       4        293.905   293.910           2   7.000000    0.005

Ratio of recommended clusters to total clusters: 0.9090909090909091
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9090909090909091
Number of measurements: 20
Hits: 10
Hit rate: 0.5

Ratio of recommended clusters to total clusters: 0.9090909090909091
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9090909090909091
Number of measurements: 12
Hits: 5
Hit rate: 0.417

=========================================

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Spectral Results for topic 41
Number of projects in topic: 108
Total number of measurements: 609
Estimated number of noise measurements: 2.0
Noise proportion: 0.003
Signal proportion: 0.997

Topic 41 cluster width stats:
count    12.0000
mean     17.5183
std      28.4818
min       0.1000
25%       1.8663
50%       2.8050
75%      23.4513
max      94.5400
dtype: float64

Cluster data frame for topic 41
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
41     9        278.175   372.715          89        7.0  94.540
       8        213.345   261.240         283        6.0  47.895
       6         85.895   115.275         178        3.0  29.380
       3        318.015   339.490          22        7.0  21.475
       7        153.135   157.830           8        4.0   4.695
       5        243.445   246.790           9        6.0   3.345
       4        265.290   267.555           5        6.0   2.265
      -1        169.695   171.695           2        5.0   2.000
       0        306.080   307.955           2        7.0   1.875
       2        144.440   146.280           2        4.0   1.840
       1        182.495   183.305           2        5.0   0.810
       10       491.685   491.785           7        8.0   0.100

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 13
Hits: 13
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 13
Hits: 13
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 7
Hits: 7
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 22
Hits: 22
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 11
Hits: 11
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 20
Hits: 19
Hit rate: 0.95

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 8
Hit rate: 0.667

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 17
Hits: 8
Hit rate: 0.471

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 14
Hits: 14
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 22
Hits: 19
Hit rate: 0.864

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

=========================================

Spectral Results for topic 42
Number of projects in topic: 29
Total number of measurements: 216
Estimated number of noise measurements: 4.0
Noise proportion: 0.019
Signal proportion: 0.981

Topic 42 cluster width stats:
count     6.0000
mean     41.3500
std      33.2574
min       0.0000
25%      16.7550
50%      39.0850
75%      70.7675
max      79.2900
dtype: float64

Cluster data frame for topic 42
               min_freq  max_freq  count_freq  band_mode  width
topic cluster
42     3        277.445   356.735          94        7.0  79.29
       4        388.605   465.815           7        8.0  77.21
       2        216.110   267.550          80        6.0  51.44
       1         88.560   115.290          30        3.0  26.73
      -1        179.205   192.635           4        5.0  13.43
       0        133.170   133.170           1        4.0   0.00

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 8
Hit rate: 0.667

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

=========================================

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\base.py:1389: ConvergenceWarning:

Number of distinct clusters (2) found smaller than n_clusters (8). Possibly due to duplicate points in X.

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Spectral Results for topic 43
Number of projects in topic: 222
Total number of measurements: 1221
Estimated number of noise measurements: 2.0
Noise proportion: 0.002
Signal proportion: 0.998

Topic 43 cluster width stats:
count    14.0000
mean     22.1296
std      25.4060
min       0.0150
25%       3.9013
50%       7.6200
75%      34.9075
max      86.2850
dtype: float64

Cluster data frame for topic 43
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
43     10       277.985   364.270         340        7.0  86.285
       9        213.595   267.645         483        6.0  54.050
       12       658.020   697.050          32        9.0  39.030
       11       455.985   492.155          12        8.0  36.170
       7        130.885   162.005         124        4.0  31.120
       6         85.160   114.845         182        3.0  29.685
       2        673.975   681.950           7        9.0   7.975
       4        202.155   209.420          13        5.0   7.265
       5        190.935   197.500          11        5.0   6.565
      -1        708.920   713.380           2        9.0   4.460
       8        167.910   171.625           9        5.0   3.715
       0        402.610   404.600           2        8.0   1.990
       1        390.620   392.110           2        8.0   1.490
       3        372.535   372.550           2        7.0   0.015

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 9
Hits: 9
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 11
Hits: 11
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 13
Hits: 13
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 9
Hits: 7
Hit rate: 0.778

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 7
Hits: 7
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 16
Hits: 16
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 16
Hits: 16
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 25
Hits: 25
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 7
Hits: 7
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 4
Hit rate: 0.5

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 21
Hits: 21
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 7
Hits: 7
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 14
Hits: 14
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 9
Hits: 9
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 7
Hits: 7
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 18
Hits: 18
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 0
Hit rate: 0.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 0
Hit rate: 0.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 11
Hits: 11
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 14
Hits: 14
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 20
Hits: 20
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 22
Hits: 20
Hit rate: 0.909

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 23
Hits: 11
Hit rate: 0.478

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 19
Hits: 19
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 7
Hits: 7
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 9
Hits: 9
Hit rate: 1.0

=========================================

Spectral Results for topic 44
Number of projects in topic: 29
Total number of measurements: 175
Estimated number of noise measurements: 7.0
Noise proportion: 0.04
Signal proportion: 0.96
BAND OVERLAP

Topic 44 cluster width stats:
count    12.0000
mean     17.6425
std      22.6102
min       0.7500
25%       2.6925
50%       3.8100
75%      35.3000
max      69.3800
dtype: float64

Cluster data frame for topic 44
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
44     8        288.560   357.940          59   7.000000  69.380
       6        160.355   201.640          20   5.000000  41.285
       7        213.550   252.480          49   6.000000  38.930
      -1        139.615   173.705           7   4.571429  34.090
       4         92.900   103.300           9   3.000000  10.400
       9        258.265   262.255           8   6.000000   3.990
       3         85.975    89.605           5   3.000000   3.630
       10       300.545   303.975           8   7.000000   3.430
       0        222.005   224.995           2   6.000000   2.990
       1        363.725   365.525           2   7.000000   1.800
       5        265.365   266.400           4   6.000000   1.035
       2        239.645   240.395           2   6.000000   0.750

=========================================

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Spectral Results for topic 45
Number of projects in topic: 77
Total number of measurements: 293
Estimated number of noise measurements: 3.0
Noise proportion: 0.01
Signal proportion: 0.99

Topic 45 cluster width stats:
count    12.0000
mean     13.7229
std      15.6125
min       0.8350
25%       4.8000
50%       7.1800
75%      18.8750
max      55.7750
dtype: float64

Cluster data frame for topic 45
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
45     8        213.345   269.120         132        6.0  55.775
       7        128.550   156.505          25        4.0  27.955
       9        337.035   358.310          52        7.0  21.275
       6         97.195   115.270          34        3.0  18.075
       5        657.860   666.890           9        9.0   9.030
       3         85.195    92.505          10        3.0   7.310
       2        643.200   650.250           7        9.0   7.050
       4        326.995   333.000          11        7.0   6.005
       10       688.960   693.875           6        9.0   4.915
       0        708.875   713.330           2        9.0   4.455
       1        673.970   675.965           2        9.0   1.995
      -1        362.030   362.865           3        7.0   0.835

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 2
Hit rate: 0.5

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 9
Hit rate: 0.75

=========================================

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Spectral Results for topic 46
Number of projects in topic: 162
Total number of measurements: 893
Estimated number of noise measurements: 8.0
Noise proportion: 0.009
Signal proportion: 0.991
BAND OVERLAP

Topic 46 cluster width stats:
count     14.0000
mean      40.0907
std       48.5735
min        0.0000
25%        4.9913
50%       24.2425
75%       53.8400
max      167.0800
dtype: float64

Cluster data frame for topic 46
               min_freq  max_freq  count_freq  band_mode    width
topic cluster
46    -1        441.410   608.490           8        8.5  167.080
       11       395.035   491.095          56        8.0   96.060
       10       276.015   366.640         128        7.0   90.625
       9        212.040   269.000         337        6.0   56.960
       8        165.375   209.855          21        5.0   44.480
       7        126.415   161.675          52        4.0   35.260
       6         85.160   115.065         257        3.0   29.905
       12       673.105   691.685          11        9.0   18.580
       5        313.580   319.920           7        7.0    6.340
       3        619.535   624.725           4        9.0    5.190
       1        452.885   457.810           3        8.0    4.925
       4        193.665   197.870           6        5.0    4.205
       2        706.205   707.865           2        9.0    1.660
       0        662.385   662.385           1        9.0    0.000

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 12
Hits: 3
Hit rate: 0.25

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 4
Hits: 0
Hit rate: 0.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 13
Hits: 13
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 9
Hits: 9
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 7
Hits: 7
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 18
Hits: 18
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 8
Hits: 5
Hit rate: 0.625

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 5
Hits: 3
Hit rate: 0.6

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 20
Hits: 20
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 20
Hits: 20
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 15
Hits: 15
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 16
Hits: 15
Hit rate: 0.938

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 1
Hits: 0
Hit rate: 0.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 6
Hits: 1
Hit rate: 0.167

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 16
Hits: 16
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 4
Hits: 3
Hit rate: 0.75

Ratio of recommended clusters to total clusters: 0.9285714285714286
Number of measurements: 6
Hits: 6
Hit rate: 1.0

=========================================

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Spectral Results for topic 47
Number of projects in topic: 99
Total number of measurements: 558
Estimated number of noise measurements: 2.0
Noise proportion: 0.004
Signal proportion: 0.996

Topic 47 cluster width stats:
count    13.0000
mean     21.1181
std      26.6883
min       1.7600
25%       1.8750
50%       7.4550
75%      29.0650
max      88.6350
dtype: float64

Cluster data frame for topic 47
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
47     10       279.510   368.145         100        7.0  88.635
       9        212.045   272.355         146        6.0  60.310
       6         84.080   115.270         232        3.0  31.190
       7        126.100   155.165          29        4.0  29.065
       11       660.205   687.590          23        9.0  27.385
       8        183.305   195.950           6        5.0  12.645
       5        414.635   422.090           6        8.0   7.455
       2        427.195   432.435           4        8.0   5.240
       4        296.415   301.640           4        7.0   5.225
       1        464.730   466.605           2        8.0   1.875
      -1        408.175   410.050           2        8.0   1.875
       3        173.100   174.975           2        5.0   1.875
       0        476.925   478.685           2        8.0   1.760

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 17
Hits: 17
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 10
Hits: 10
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 3
Hit rate: 0.375

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 15
Hits: 15
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 16
Hits: 16
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 16
Hits: 16
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 11
Hits: 11
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 9
Hits: 9
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 20
Hits: 20
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 15
Hits: 15
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

=========================================

Spectral Results for topic 48
Number of projects in topic: 46
Total number of measurements: 290
Estimated number of noise measurements: 4.0
Noise proportion: 0.014
Signal proportion: 0.986

Topic 48 cluster width stats:
count     6.0000
mean     33.4733
std      29.6601
min       0.0000
25%      15.3575
50%      24.3825
75%      52.6487
max      77.6550
dtype: float64

Cluster data frame for topic 48
               min_freq  max_freq  count_freq  band_mode   width
topic cluster
48     4        278.180   355.835          75        7.0  77.655
       3        212.675   273.270         175        6.0  60.595
       1         84.505   113.315          28        3.0  28.810
      -1        840.495   860.450           4       10.0  19.955
       2        170.790   184.615           7        5.0  13.825
       0        139.055   139.055           1        4.0   0.000

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\base.py:1389: ConvergenceWarning:

Number of distinct clusters (2) found smaller than n_clusters (8). Possibly due to duplicate points in X.

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 22
Hits: 22
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 10
Hits: 10
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 17
Hits: 17
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 2
Hit rate: 0.667

=========================================

c:\Users\krish\miniconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

Spectral Results for topic 49
Number of projects in topic: 241
Total number of measurements: 1559
Estimated number of noise measurements: 4.0
Noise proportion: 0.003
Signal proportion: 0.997

Topic 49 cluster width stats:
count     15.0000
mean      29.4913
std       34.7483
min        0.1700
25%        5.4175
50%        8.0300
75%       41.5725
max      106.2550
dtype: float64

Cluster data frame for topic 49
               min_freq  max_freq  count_freq  band_mode    width
topic cluster
49     12       391.245   497.500         180        8.0  106.255
       11       276.105   371.755         261        7.0   95.650
       10       211.975   273.955         535        6.0   61.980
       9        159.265   209.755          35        5.0   50.490
       8        129.335   161.990          84        4.0   32.655
       13       657.640   688.520          26        9.0   30.880
       7         84.980   114.985         409        3.0   30.005
       4        169.800   177.830           7        5.0    8.030
       0        604.965   610.920           4        9.0    5.955
       6        620.965   626.915           4        9.0    5.950
       3        844.275   849.695           4       10.0    5.420
      -1        827.780   833.195           4       10.0    5.415
       2        648.000   649.875           2        9.0    1.875
       1        442.035   443.675           2        8.0    1.640
       5        437.635   437.805           2        8.0    0.170

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 16
Hits: 12
Hit rate: 0.75

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 16
Hits: 16
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 16
Hits: 14
Hit rate: 0.875

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 4
Hit rate: 0.667

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 16
Hits: 16
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 24
Hits: 24
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 24
Hits: 24
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 16
Hits: 16
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 16
Hits: 16
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 4
Hit rate: 0.5

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 24
Hits: 24
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 16
Hits: 16
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 3
Hit rate: 0.375

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 14
Hits: 14
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 18
Hits: 18
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 8
Hits: 8
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 4
Hit rate: 0.333

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 20
Hits: 20
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 16
Hits: 16
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 16
Hits: 3
Hit rate: 0.188

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 26
Hits: 24
Hit rate: 0.923

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 10
Hits: 10
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 5
Hits: 5
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 2
Hits: 2
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 12
Hits: 12
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 4
Hits: 4
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 6
Hits: 6
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 1
Hits: 1
Hit rate: 1.0

Ratio of recommended clusters to total clusters: 1.0
Number of measurements: 3
Hits: 3
Hit rate: 1.0

=========================================

Total number of clusters across topics: 533
Number of test projects with at least one measurement match: 768
Ratio of test project hits to number of test projects: 0.966
Average hit rate per project: 0.9079
Standard Deviation of hit rate per project: 0.2332

### Build full topic-measurement data frame

In [78]:
topic_measurement_frame = pd.concat(topic_measurement_stat_list)

In [79]:
topic_measurement_frame.loc[0]

             med_freq  band    project_code  cluster_label
measurement
0             258.110     6  2017.1.00598.S              8
1             260.035     6  2017.1.00598.S              8
2             261.355     6  2017.1.00598.S              8
3             263.305     6  2017.1.00598.S              8
4             261.775     6  2017.1.00598.S              8
...               ...   ...             ...            ...
120           247.295     6  2017.1.00113.S              5
121           249.065     6  2017.1.00113.S              5
122           261.235     6  2017.1.00113.S              8
123           263.005     6  2017.1.00113.S              8
124           230.540     6  2019.2.00190.S              8

[125 rows x 4 columns]

### Visualization of Spectral Clustering on Topics
Choose a topic in `inspect_topic` and let it rip! It uses the `topic_measurement_frame` to generate the images. There's a little bit of extra processing though, so we create a helper dataframe, `inspect_topic_frame` to make sure everything runs smoothly.

* This should probably become a function, at least the plotting part
* Maybe check out plotly "strip" charts

In [80]:
inspect_topic = 0
inspect_topic_frame = topic_measurement_frame.loc[inspect_topic]

inspect_topic_frame = inspect_topic_frame.sort_values('cluster_label', ascending=False)
inspect_topic_frame.cluster_label = inspect_topic_frame.cluster_label.astype('str')

# Add noise binary column for plot symbol
inspect_topic_frame['noise'] = np.where(inspect_topic_frame.cluster_label == '-1', 1, 0)

# Noise and Signal
itf_noise = inspect_topic_frame.noise.sum()
itf_signal = inspect_topic_frame.shape[0] - itf_noise

# Set symbols for plot
# We set all points to be 'circle' using the px number 0, and then change noise to 'x'
symbols = list(np.zeros(np.unique(inspect_topic_frame.cluster_label).shape[0], 'int'))
symbols[-1] = 'x'

# Create plot
fig = px.scatter(inspect_topic_frame,
                 x='med_freq',
                 y='cluster_label',
                 color='cluster_label',
                 symbol='cluster_label',
                 symbol_sequence=symbols,
                 title=f"Spectral Generated Clusters for Topic {inspect_topic} <br><sup>{itf_signal} Clustered Measurements with {itf_noise} Noise Measurements</sup>",
                 labels={
                     'med_freq':'Median Frequency (GHz)',
                     'index':'Index',
                     'cluster_label':'Cluster Label'
                 })
fig.update_traces(marker={'size': 15, 'opacity':0.5})

fig.show()

In [81]:
topic_measurement_frame.loc[25]

             med_freq  band    project_code  cluster_label
measurement
0             140.935     4  2015.1.00117.S              7
1             142.815     4  2015.1.00117.S              7
2             152.935     4  2015.1.00117.S              1
3             154.815     4  2015.1.00117.S              1
4              96.165     3  2015.1.00117.S              6
...               ...   ...             ...            ...
134           159.115     4  2017.1.00321.S              1
135           132.550     4  2017.1.00321.S              7
136           134.415     4  2017.1.00321.S              7
137           144.465     4  2017.1.00321.S              7
138           146.285     4  2017.1.00321.S              7

[139 rows x 4 columns]

### Build full topic-cluster data frame

## **THIS IS A VERY IMPORTANT DATAFRAME IT THIS IS THE CORE RESULT OF THE MINING APPROACH!!!!!!**

This data frame holds all of the cluster info for each of the generated topics

* Pretty much all of the cluster stats in the code cell above can be derived from this

In [82]:
topic_cluster_stats = pd.concat(topic_cluster_stat_list)

In [83]:
topic_cluster_stats.loc[0].sort_values('count_proj', ascending=False)

,mean_freq,min_freq,max_freq,count_freq,count_proj,band_min,band_max,band_mode,width
cluster,,,,,,,,,
8,243.482647,216.860,269.140,51,9,6,6,6.0,52.280
5,250.560909,244.245,254.530,11,4,6,6,6.0,10.285
7,102.378125,86.845,110.895,24,3,3,3,3.0,24.050
-1,340.390000,338.130,342.875,4,2,7,7,7.0,4.745
0,348.951250,345.945,351.930,4,2,7,7,7.0,5.985
1,178.390000,175.765,182.000,3,1,5,5,5.0,6.235
2,165.958333,164.165,168.005,3,1,5,5,5.0,3.840
3,329.952500,329.325,330.580,2,1,7,7,7.0,1.255
4,145.757500,144.915,146.600,2,1,4,4,4.0,1.685
6,134.082500,133.295,134.870,2,1,4,4,4.0,1.575
9,458.794737,450.495,466.225,19,1,8,8,8.0,15.730

In [84]:
topic_cluster_stats.sample(10)

,,mean_freq,min_freq,max_freq,count_freq,count_proj,band_min,band_max,band_mode,width
topic,cluster,,,,,,,,,
28,2,252.143750,250.690,253.665,4,1,6,6,6.0,2.975
1,2,185.745000,184.845,186.645,2,1,5,5,5.0,1.800
14,6,109.058125,107.895,110.115,8,4,3,3,3.0,2.220
36,-1,169.352500,164.265,174.440,2,1,5,5,5.0,10.175
49,4,173.712857,169.800,177.830,7,4,5,5,5.0,8.030
26,7,141.179375,133.795,146.970,8,1,4,4,4.0,13.175
48,-1,849.531250,840.495,860.450,4,1,10,10,10.0,19.955
43,11,474.434167,455.985,492.155,12,3,8,8,8.0,36.170
47,8,188.473333,183.305,195.950,6,2,5,5,5.0,12.645
26,4,342.466875,339.470,345.305,8,3,7,7,7.0,5.835

### Compute cluster signal to noise proportions

In [85]:
sn_list = []
for clst in np.unique(topic_cluster_stats.index.get_level_values(0)):
    clst_sig = np.sum(topic_cluster_stats.loc[topic_cluster_stats.index.get_level_values(1) != -1].loc[clst].count_freq)
    clst_noise = np.sum(topic_cluster_stats.loc[topic_cluster_stats.index.get_level_values(1) == -1].loc[clst].count_freq)
    sn_list.append({'signal':clst_sig, 'noise':clst_noise})

In [86]:
signal_noise_frame = pd.DataFrame(sn_list)
signal_noise_frame.index.name = 'cluster'
signal_noise_frame['signal_prop'] = (signal_noise_frame.signal)/(signal_noise_frame.signal + signal_noise_frame.noise)
signal_noise_frame['noise_prop'] = (signal_noise_frame.noise)/(signal_noise_frame.signal + signal_noise_frame.noise)
signal_noise_frame

         signal  noise  signal_prop  noise_prop
cluster
0           121      4     0.968000    0.032000
1           203      6     0.971292    0.028708
2           252      8     0.969231    0.030769
3            72      2     0.972973    0.027027
4           289      4     0.986348    0.013652
5           286      5     0.982818    0.017182
6           264     90     0.745763    0.254237
7           142      1     0.993007    0.006993
8           174      2     0.988636    0.011364
9           402     12     0.971014    0.028986
10         1226      8     0.993517    0.006483
11           33      3     0.916667    0.083333
12          837      1     0.998807    0.001193
13          627      4     0.993661    0.006339
14           93      2     0.978947    0.021053
15          155      2     0.987261    0.012739
16          295     28     0.913313    0.086687
17          478      1     0.997912    0.002088
18          265      4     0.985130    0.014870
19          361      2     0.994490    0.005510
20          246      3     0.987952    0.012048
21          611      3     0.995114    0.004886
22          139      4     0.972028    0.027972
23          233     12     0.951020    0.048980
24          797      2     0.997497    0.002503
25          137      2     0.985612    0.014388
26          112      4     0.965517    0.034483
27          118      2     0.983333    0.016667
28          183      9     0.953125    0.046875
29          125      4     0.968992    0.031008
30          232      4     0.983051    0.016949
31          131      4     0.970370    0.029630
32          147      4     0.973510    0.026490
33          232      4     0.983051    0.016949
34          123      5     0.960938    0.039062
35          146      4     0.973333    0.026667
36          183      2     0.989189    0.010811
37          168      4     0.976744    0.023256
38           76      1     0.987013    0.012987
39          753      6     0.992095    0.007905
40           82      3     0.964706    0.035294
41          607      2     0.996716    0.003284
42          212      4     0.981481    0.018519
43         1219      2     0.998362    0.001638
44          168      7     0.960000    0.040000
45          290      3     0.989761    0.010239
46          885      8     0.991041    0.008959
47          556      2     0.996416    0.003584
48          286      4     0.986207    0.013793
49         1555      4     0.997434    0.002566

In [87]:
signal_noise_frame.describe()

            signal      noise  signal_prop  noise_prop
count    50.000000  50.000000    50.000000   50.000000
mean    346.540000   6.220000     0.974408    0.025592
std     331.312801  12.805117     0.037630    0.037630
min      33.000000   1.000000     0.745763    0.001193
25%     139.750000   2.000000     0.970531    0.008168
50%     232.000000   4.000000     0.983192    0.016808
75%     391.750000   4.750000     0.991832    0.029469
max    1555.000000  90.000000     0.998807    0.254237

## Inspect topic-clusters

In [88]:
topic_cluster_stats.describe()

,mean_freq,min_freq,max_freq,count_freq,count_proj,band_min,band_max,band_mode,width
count,533.000000,533.000000,533.00000,533.000000,533.000000,533.000000,533.000000,533.000000,533.000000
mean,299.837739,289.142458,311.95591,33.091932,6.011257,5.996248,6.067542,6.023581,22.813452
std,185.099164,185.847621,186.90106,69.598803,10.620941,1.967782,1.970443,1.954946,50.257074
min,37.103333,36.080000,38.02000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,155.229375,150.025000,161.99000,3.000000,1.000000,4.000000,4.000000,4.000000,2.000000
50%,248.341341,239.645000,267.85500,7.000000,2.000000,6.000000,6.000000,6.000000,6.905000
75%,353.716250,345.815000,366.69000,28.000000,5.000000,7.000000,7.000000,7.000000,28.695000
max,903.982500,901.170000,906.79500,535.000000,83.000000,10.000000,10.000000,10.000000,504.010000

In [89]:
topic_cluster_stats.width.describe()

count    533.000000
mean      22.813452
std       50.257074
min        0.000000
25%        2.000000
50%        6.905000
75%       28.695000
max      504.010000
Name: width, dtype: float64

In [90]:
topic_cluster_stats.query('width > 10 and cluster != -1')\
    .sort_values(['count_freq', 'width'], ascending=False)\
    .head(50)

                mean_freq  min_freq  max_freq  count_freq  count_proj  \
topic cluster
49    10       242.512757   211.975   273.955         535          77
43    9        228.312557   213.595   267.645         483          83
10    6         98.277436    85.010   115.270         470          68
      8        225.221812   212.190   247.215         436          67
49    7         99.135147    84.980   114.985         409          57
12    0        102.837201    85.120   115.275         343          45
24    6         94.008548    85.450   115.320         341          48
43    10       333.229265   277.985   364.270         340          63
46    9        231.509540   212.040   269.000         337          55
21    8        223.376830   213.010   236.455         317          41
41    8        225.485318   213.345   261.240         283          37
24    8        224.519065   215.200   234.975         262          33
49    11       316.728180   276.105   371.755         261          36
46    6        103.447374    85.160   115.065         257          42
17    7        101.107711    85.045   115.125         249          38
39    9        238.860717   216.380   265.890         244          24
12    3        231.004393   212.145   272.820         239          31
39    10       338.830696   278.600   365.370         237          26
47    6        103.874677    84.080   115.270         232          39
13    7         99.381317    84.565   115.270         224          39
9     8        230.532434   214.795   268.605         189          27
43    6         99.273901    85.160   114.845         182          32
49    12       436.214222   391.245   497.500         180          28
41    6         98.846798    85.895   115.275         178          30
48    3        229.887286   212.675   273.270         175          28
13    9        241.409128   216.115   273.905         172          25
19    7        225.420382   212.530   255.550         170          43
10    9        334.852852   277.000   372.665         149          31
4     7        102.209388    85.025   115.265         147          20
47    9        235.440205   212.045   272.355         146          27
19    8        341.003938   329.320   357.895         146          41
9     9        342.541414   299.680   359.135         145          27
30    3        236.553531   213.120   264.270         143          14
23    10       233.913794   216.110   261.250         141          21
20    7        223.689964   213.075   246.400         140          24
39    6         99.975827    84.730   113.490         139          16
45    8        232.137689   213.345   269.120         132          27
37    7        245.358385   217.070   262.990         130          13
46    10       339.770508   276.015   366.640         128          25
18    7        100.171600    84.530   115.180         125          18
43    7        145.748185   130.885   162.005         124          21
5     5        248.897521   215.225   273.955         119          12
6     6        218.651144   213.095   224.750         118          26
4     8        226.939612   215.880   246.005         116          17
12    4        338.105965   277.010   364.165         114          22
28    8        225.054670   212.505   234.630         106          16
24    9        322.231373   275.845   359.900         102          18
5     3         98.364406    85.250   114.705         101          12
47    10       338.925750   279.510   368.145         100          15
16    6        102.205400    85.015   114.890         100          10

               band_min  band_max  band_mode    width
topic cluster
49    10              6         6        6.0   61.980
43    9               6         6        6.0   54.050
10    6               3         3        3.0   30.260
      8               6         6        6.0   35.025
49    7               3         3        3.0   30.005
12    0               3         3        3.0   30.155
24    6               3         3        3.0   29.870
43    10              7         7        7.0   86.285
46    9               6         6        6.0   56.960
21    8               6         6        6.0   23.445
41    8               6         6        6.0   47.895
24    8               6         6        6.0   19.775
49    11              7         7        7.0   95.650
46    6               3         3        3.0   29.905
17    7               3         3        3.0   30.080
39    9               6         6        6.0   49.510
12    3               6         6        6.0   60.675
39    10              7         7        7.0   86.770
47    6               3         3        3.0   31.190
13    7               3         3        3.0   30.705
9     8               6         6        6.0   53.810
43    6               3         3        3.0   29.685
49    12              8         8        8.0  106.255
41    6               3         3        3.0   29.380
48    3               6         6        6.0   60.595
13    9               6         6        6.0   57.790
19    7               6         6        6.0   43.020
10    9               7         7        7.0   95.665
4     7               3         3        3.0   30.240
47    9               6         6        6.0   60.310
19    8               7         7        7.0   28.575
9     9               7         7        7.0   59.455
30    3               6         6        6.0   51.150
23    10              6         6        6.0   45.140
20    7               6         6        6.0   33.325
39    6               3         3        3.0   28.760
45    8               6         6        6.0   55.775
37    7               6         6        6.0   45.920
46    10              7         7        7.0   90.625
18    7               3         3        3.0   30.650
43    7               4         4        4.0   31.120
5     5               6         6        6.0   58.730
6     6               6         6        6.0   11.655
4     8               6         6        6.0   30.125
12    4               7         7        7.0   87.155
28    8               6         6        6.0   22.125
24    9               7         7        7.0   84.055
5     3               3         3        3.0   29.455
47    10              7         7        7.0   88.635
16    6               3         3        3.0   29.875

### Check to see there are no clusters spanning bands

In [91]:
topic_cluster_stats.query('band_max - band_min > 1 and cluster != -1')\
    .sort_values(['width', 'count_freq'], ascending=False)\
    .head(30)

Empty DataFrame
Columns: [mean_freq, min_freq, max_freq, count_freq, count_proj, band_min, band_max, band_mode, width]
Index: []

### Inspect an individual topic's clusters

In [92]:
topic_cluster_stats.loc[0]

,mean_freq,min_freq,max_freq,count_freq,count_proj,band_min,band_max,band_mode,width
cluster,,,,,,,,,
-1,340.390000,338.130,342.875,4,2,7,7,7.0,4.745
0,348.951250,345.945,351.930,4,2,7,7,7.0,5.985
1,178.390000,175.765,182.000,3,1,5,5,5.0,6.235
2,165.958333,164.165,168.005,3,1,5,5,5.0,3.840
3,329.952500,329.325,330.580,2,1,7,7,7.0,1.255
4,145.757500,144.915,146.600,2,1,4,4,4.0,1.685
5,250.560909,244.245,254.530,11,4,6,6,6.0,10.285
6,134.082500,133.295,134.870,2,1,4,4,4.0,1.575
7,102.378125,86.845,110.895,24,3,3,3,3.0,24.050
8,243.482647,216.860,269.140,51,9,6,6,6.0,52.280
9,458.794737,450.495,466.225,19,1,8,8,8.0,15.730

### Histogram of topic clusters

**Compare this to the scatter plot above. These two charts in tandem are good. Maybe we can combine them somehow**

Hover info needs work

In [93]:
import plotly.graph_objects as go
def plot_topic_clusters(tc_frame:pd.DataFrame, topic:int):
    figure = go.Figure()
    figure.add_trace(
        go.Bar(
            x=tc_frame.query(f'topic== {topic} and cluster != -1').mean_freq,
            y=tc_frame.query(f'topic== {topic} and cluster != -1').count_freq,
            #name=dict(color=tc_frame.query(f'topic== {topic} and cluster != -1').index.get_level_values(level=1)),
            width=tc_frame.query(f'topic== {topic} and cluster != -1').width.to_list()
            # hoverinfo=(
            #     tc_frame.query(f'topic== {topic} and cluster != -1').min_freq,
            #     tc_frame.query(f'topic== {topic} and cluster != -1').max_freq
            # )
        )
    )
    figure.update_layout(
    title=(f'Areas of Interest for Topic {topic}'),
    xaxis_title='Frequency (GHz)',
    yaxis_title='Count of Measurements',
    )
    figure.show()

In [94]:
plot_topic_clusters(topic_cluster_stats, 25)